- src/qibolab/platforms/abstract.py
- src/qibolab/runcards/tii5q.yml
Updates `platform.reload_settings` to load new settings for frequencies, etc. if the runcard yaml is updated. This is included in #166 but I do not think this will be merged soon, so I fix this here seperately because I believe it is relevant for passing parameters from calibration to the next in qibocal (see qiboteam/qibocal#82).
> Fix `platform.reload_settings`

- src/qibolab/pulses.py
- src/qibolab/runcards/tii5q.yml
Sets the global phase of the readout pulse to 0 so that the probability calculation is independent of the start time of the readout. 
I have updated the `mean_gnd_states` and `mean_exc_states` for qubit 2 of tii5q and the probability calculation seems to work well for this qubit, at least for the ground state, the excited state (with one RX or two RX90) and the superposition state (one RX90). We need to make a few more tests to make sure this is robust, but it should be sufficient to run some randomized benchmarking.
We need to re-calibrate the mean states with the new phase in order to make the rest of the qubits work.
> Fix probability calculation

- src/qibolab/instruments/qblox.py
This PR improves the way in which waveforms and programs are uploaded to Qblox devices.
Qblox have recently advised that the dictionary that contains the waveforms and the program can be uploaded directly to the device, without having to save it first as a json file.
This simple change is expected to accelerate some routines in which either the waveforms or the program change from one iteration to the next.
```python
for sequencer in self._sequencers[port]:
qblox_dict[sequencer] = {
"waveforms": sequencer.waveforms,
"weights": sequencer.weights,
"acquisitions": sequencer.acquisitions,
"program": sequencer.program,
}
self.device.sequencers[sequencer.number].sequence(qblox_dict[sequencer])
```
> Accelerate waveforms and program upload

- src/qibolab/tests/test_transpilers_connectivity.py
- src/qibolab/transpilers/connectivity.py
This PR fixes an issue regarding the transpilation of a circuit containing unitary gates.
Code to raise the error:
```python
import qibo
from qibo import gates
from qibo.models import Circuit
qibo.set_backend("qibolab", platform="tii5q")
qubit = 2
c = Circuit(5)
c.add(gates.Unitary(gates.H(0).matrix,qubit))
c.add(gates.M(qubit))
result = c(nshots=5000)
```
I've also implemented tests for this particular case.
@wilkensJ feel free to use this branch for RB in qibocal.
Checklist:
> Fix bug with unitary gates

- .github/workflows/selfhosted.yml
Generalizes the script that uses labels to submit qpu tests. Now any label of the form `run-on-*` will trigger a test that is submitted to the queue `*`, so that we don't need to update the code every time we change the queue structure, we just need to change the label names. @scarrazza let me know if you agree.
Checklist:
> Use arbitrary queue names for qpu tests

- src/qibolab/platform.py
- src/qibolab/runcards/qw5q_gold.yml
@aorgazf, here is the runcard for the qw5q_gold. First, I've just tested it with `qibocal/main` and this branch. It gives the following results: 
http://login.qrccluster.com:9000/UQpuzUbgQLWLG42WPU_Shg==
I was mainly focused on Qubit 2, so there is quite a lot to do. 
It looks like the frequency has shifted, not too sure why. I guess that it is one thing to characterize. I would also advise looking into the following:
- Getting T1 / T2 multiple times. It looks like the frequencies are changing, but I didn't spend time on this at all. 
- Writing and testing a routine to optimize the TWPA frequency and power to achieve high fidelities. Note that too much power kills the signal, 0dBm is what I would recommend to start optimizing the frequency. All the resonators should be considered in that …
> qw5q_gold runcard

- setup.py
Hi,
Rohde & Schwarz oscillators are needed again, not for up/down conversion, but for biassing TWPAs.
Their drivers require pyvisa-py library, which must have been removed a while back unintentionally. 
This PR adds the installation of pyvisa-py version 0.5.3 back to TII system dependencies.
The installation has succeeded on a windows machine.
No documentation update required.
Checklist:
> Include pyvisa-py library in qibolab dependencies [tiiq]

- src/qibolab/platform.py
Hi,
Currently we have multiple QPUs, each with its own runcard (qw5q_gold.yml, iqm5q.yml, etc.).
In qibocal action runcard, one can only specify the platform, but not the platform runcard.
When we want to use a new runcard, we used to modify platform.py to load any of these QPUs with multiqubit platform like this:
```python
def Platform(name, runcard=None):
"""..."""
if not runcard:
from qibolab.paths import qibolab_folder
runcard = qibolab_folder / "runcards" / f"{name}.yml"
if name == "tii1q" or name == "qw5q_gold" or name == "qili":  #<- HERE
from qibolab.platforms.multiqubit import MultiqubitPlatform as Device
elif name == "icarusq":
from qibolab.platforms.icplatform import ICPlatform as Device
elif name == "dummy":
```
To avoid having to do this and until qibocal suports platform and …
> Temporarily set multiqubit as default platform for multiple runcards

- src/qibolab/runcards/tii1q_b1.yml
Dear All,
Please find a runcard for **tii1q_b1** qpu.
This processor belongs to the first batch fabricated by TII. It is installed at the XLD and controlled with Qblox Cluster and R&S local oscillator to drive the TWPA.
If you have not done it already, please ensure your environment has the latest version of pivisa-py and qblox-instruments 0.7.0:
```
pip install pyvisa-py
pip install qblox-instruments==0.7.0
```
The chip is installed in `reem2` node partition `tii1q_b1`.
My launching batch file looks like this:
```bash
#!/bin/bash
#SBATCH --job-name=qibocal_1q
#SBATCH --partition=tii1q_b1
#SBATCH --output=logs/latest_experiment_1q.log
qq ~/qibocal_1q.yml -o reports/$(date +'%Y%m%d')_latest_1q -f
```
Here are the fidelities measured with it:
Checklist:
> tii1q_b1 QPU runcard

- setup.py
- src/qibolab/instruments/qblox.py
- src/qibolab/runcards/qw5q_gold.yml
Hi all,
We have upgraded TII Qblox clusters to firmware [v0.2.2](https://gitlab.com/qblox/releases/cluster_releases/-/releases/v0.2.2).
The version of the python library needs to be upgraded to [v.0.7.0](https://gitlab.com/qblox/packages/software/qblox_instruments/-/releases/v0.7.0).
In order to use qblox drivers, one needs to update qblox-instruments library using `pip install qblox-instruments==0.7.0'
The driver needed to be amended slightly so that it clears the acquisition memory before playing a sequence.
Previously, with hardware demodulation, the only way to clear that memory was uploading all waveforms and program again, rendering ~100ms extra overhead.
The new version has been tested for a few weeks and it seems to work fine.
I would like to test the performance of the driver …
> Update qblox-instruments to version 0.7.0

- src/qibolab/instruments/qblox.py
Hi,
This PR fixes a recently found issue that manifested in certain (not very common) scenarios, when executing multiple calibration actions in qibocal.
The driver initialises the `noc_freq` to 0 at setup and it is then set during the first execution.
Subsequent calibration routines were calling `platform.reload_settings()` (which was resetting the `nco_freq`) to 0, however, if the sequence to be played was the same as the one in the last calibration routine, the driver would used the cached values and skipped setting .
To fix it, on every setup, the pulse sequence hash is cleared (forcing a reevaluation).
The bug can be reproduced with the following action runcard:
```yaml
platform: qblox
runcard: qibolab/src/qibolab/runcards/tii1q_b1.yml
qubits: [0]
format: csv
actions: …
```
> Fix initialisation issue

- src/qibolab/platforms/abstract.py
Fixes a minor bug in loading the platform native two-qubit gates.
```python
if "two_qubit" in self.native_gates.keys():
for pairs, gates in self.native_gates["two_qubit"].items():
self.two_qubit_natives |= set(gates.keys())
```
Checklist:
> Fix minor bug in loading the platform native two-qubit gates

- .github/workflows/rules.yml
- src/qibolab/runcards/dummy.yml
- src/qibolab/runcards/multiqubit_icarusq.yml
- src/qibolab/runcards/multiqubit_icarusqfpga.yml
- src/qibolab/runcards/qili.yml
- src/qibolab/runcards/tii1q_b1.yml
- src/qibolab/runcards/tii1q_b4_200U.yml
Hi,
This PR updates all runcards `qubit_channel_map` setting in line with the changes introduced in PR #242.
In that PR a new role of instrument was introduced: `bias` so the `qubit_channel_map` needs to be updated so that, for each qubit, it specifies the biassing channel.
Please note that for non-fluxable qubits that QubitFlux and QubitBias channels can be set to null:
```python
qubit_channel_map: # [ReadOut, QubitDrive, QubitFlux, QubitBias]
0: [1_ro, 1_qb, null, null]
```
I have labelled this PR as urgent as without it, `tii1q_b1` (our current chip in production) does not work (it should have been updated in PR #242)
Checklist:
> Update runcards qubit_channel_map

- .github/codecov.yml
Another chapter in the unsuccessful saga about the fight against Codecov noise...
Here the reference:
https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml
Checklist:
> Annotations are not comments

- src/qibolab/result.py
This PR fixes a bug in `ExecutionResults` which was causing qibocal main to not work with the current main of qibolab.
This could require some changes in qiboteam/qibocal#195. I think that it is important to merge this now if we planning to release both qibocal and qibolab shortly.
Checklist:
> Fix bug in `ExecutionResults`

- .github/workflows/selfhosted.yml
- pyproject.toml
- qputests.sh
- slurmjob.sh
Final implementation of #265 with the commits squashed to one to clean history. I think this should work but I still need to check how the coverage is logged in the website.
It appears that the coverage is increased by 13% since parts of the instrument code are now included. However I think the coverage of the test files is not logged properly because I am using symbolic links to put them in the /tmp/ directory.
Checklist:
> Upload coverage from selfhosted

- src/qibolab/instruments/dummy.py
- src/qibolab/platform.py
- src/qibolab/runcards/dummy.yml
Moves the functionality of `DummyPlatform` to a `DummyInstrument` that is controlled by the `DesignPlatform`. Since instruments are lower-level qibolab objects, this allows us to test more code (such as the `DesignPlatform` and channels) using the `DummyInstrument`, without access to qpu. It also moves towards the direction of having a single platform that can control different instruments.
Checklist:
> Move `DummyPlatform` to `DummyInstrument`

- src/qibolab/instruments/qm.py
- src/qibolab/instruments/qmsim.py
- src/qibolab/instruments/rohde_schwarz.py
- tests/conftest.py
- tests/test_instruments_qm.py
- tests/test_instruments_qmsim.py
Implements some improvements to the QM driver following some comments by @AleCandido that were not implemented during the first pass, particularly:
* https://github.com/qiboteam/qibolab/pull/259#discussion_r1066875355: dataclass to replace the QM config dictionary
* https://github.com/qiboteam/qibolab/pull/308#pullrequestreview-1293366305: simplified `sweep_recursion`
and also adds some tests using the QM simulator, for sweepers and the SNZ pulse.
I am basing this to qmsimtests as it is the only way to ensure that I am not breaking something in the driver, since we are not testing with a qpu. Both PRs should be okay to merge to main.
Checklist:
> Improvements to QM driver

- src/qibolab/platforms/abstract.py
- src/qibolab/platforms/multiqubit.py
- src/qibolab/runcards/qili1q_os2.yml
- src/qibolab/runcards/qw5q_gold.yml
This should fix a bug related to multiplex when using qblox.
I've also introduced a `resonator_type` in the runcard to correct the `lorentzian_fitting` as mentioned by @aorgazf.
Checklist:
> Fixing bug related to multiplex

- src/qibolab/backends.py
After merging #322 an error is raised if `initial_state` is `None`. Instead the default |00...0> (ground state) should be used.
Checklist:
> Allow executing circuit with `None` initial state

- src/qibolab/platforms/multiqubit.py
This PR fixes the issue #329 Multiplex not working for QBlox, for all routines except for the precision scans of the spectroscopies. 
The precision scans are going to be removed in qibocal https://github.com/qiboteam/qibocal/pull/270, soon, until then, one can comment out the precision sections of the resonator and qubit spectroscopies.
Checklist:
> Bug fix in qblox multiqubit platform affecting multiplexed readout

- src/qibolab/platforms/multiqubit.py
Hi, this PR makes it possible to use qblox qcm offsets to bias qubits flux. In a similar fashion as it is done with QM.
Checklist:
> Add support for biasing qubits with qblox qcm offsets

- setup.py
- src/qibolab/pulses.py
Hi, this PR fixes issue #328
Fix call to Pulse.copy() method and rename `PulseSequence.deep_copy()` as `PulseSequence.copy()` for consistency.
Checklist:
> Fix call to Pulse.copy() method, closes #328

- src/qibolab/instruments/qblox.py
Fixing bug introdued in the new firmware of qblox. Related with PR #347.
Excluding read-only parameter sequence from ClusterQRM_RF
Checklist:
> exclude read-only parameter sequence

- src/qibolab/runcards/qw5q_gold_qblox.yml
This PR includes the latest characterisation of qw5q_gold QPU.
To use it please refer to the ![qrccluster wiki](https://github.com/qiboteam/qrccluster/wiki/QPU-Status)
All 5 qubits seem to be working although q4 readout requires further work. I would then recommend using qubits q0 - q4.
q0, q2 and q3 have assignment fidelities above 0.9
Checklist:
> qw5q_gold runcard as of 20230331 12:00

- src/qibolab/instruments/rfsoc.py
Fixing the amplitude sweeper for the rfsoc driver (solving #377).
In the multiqubit version the sweeper will be done in a different way and the code will be more clean, for now this should work.
Checklist:
> Fixing rfsoc amplitude sweeps

- src/qibolab/instruments/rfsoc.py
- src/qibolab/platform.py
This PR integrates the Erasynth local oscillator into the ZCU111 driver. The local oscillator is needed to upconvert and downconvert the readout.
Checklist:
> Intregrating Erasynth LO control in the driver

- src/qibolab/runcards/qw5q_gold_qblox.yml
Update `qw5q_gold_qblox` runcard with new classification parameters following qiboteam/qibocal#305.
Checklist:
> Correct classification parameters in runcard

- src/qibolab/instruments/erasynth.py
- src/qibolab/instruments/rfsoc.py
- src/qibolab/platform.py
- tests/test_instruments_rfsoc.py
Here I tried to add some function to automatically look for a valid LO frequency given a sequence.
This is needed, in some cases at least, because the firmware for multiplexed readout makes the multiplexed DAC have very small bands of possible frequencies.
In particular they are limited by `(fs/32)(2i + 1)` where fs is the ADC sampling frequency (3072 MHz).
This implementation is very slow because it changes the LO at every execute_pulse_sequences, but avoids errors.
We could improve this easily by just checking for collisions and then, only if there are some, looking for a good LO.
Also, this is now done only for pulse sequences, but would be important in particular for sweepers.
Checklist:
> ZCU111-driver: auto searching LO for not conflicting frequencies

- src/qibolab/platforms/abstract.py
- src/qibolab/platforms/multiqubit.py
- src/qibolab/platforms/platform.py
**To test:**
You can `srun -p qw5q_gold python THIS`: 
```python
from qibolab import Platform
platform = Platform("qblox", runcard="/home/users/maxime.hantute/qibolab/src/qibolab/runcards/qw5q_gold_qblox.yml")
platform.connect()
platform.setup()
platform.start()
platform.set_lo_twpa_frequency(0, 5.0e9)
platform.set_lo_twpa_power(0, -10.0)
platform.stop()
platform.disconnect()
```
**Proof that it works:**
**Comment:**
This is far from optimal because it would only work with a QPU with one feedline and one TWPA, but we should migrate multiqubit to `design` anyway so I think that it is acceptable for now anyway. 
Checklist:
> Exposing TWPA parameters for abstract and multiqubit

- src/qibolab/instruments/rfsoc.py
With this PR, the qibolab rfsoc driver will raise itself the errors that happen in the server.
At the moment, when the server encounters an error, the client just print "Aborted"
Checklist:
> RFSoC: receive server errors

- .github/workflows/selfhosted.yml
- src/qibolab/designs/channels.py
- src/qibolab/platforms/platform.py
- tests/test_designs_channels.py
- tests/test_instruments_erasynth.py
- tests/test_platforms.py
Some of the qpu tests were failing were run with the rfsoc because local oscillators and flux biases were not present.
I tried to fix them.
Checklist:
> Fix qpu tests for rfsoc

- src/qibolab/instruments/rfsoc.py
- src/qibolab/platforms/platform.py
I should have updated the rfsoc driver in compliance to the updated in ExecutionParameters and the new results objects.
I still didn't test anything.
Something that could be useful to others, but can also be removed if you don't like it, is the `ExecutionParameters.get_results_type()` function.
Checklist:
> Rfosc ExecutionParameters, New Results

- src/qibolab/pulses.py
- tests/test_pulses.py
This PR would help me in the development of the new version of the rfsoc driver, these are changes that I could do in the driver itself, but it makes sense to have them in main qibolab.
List of changes:
* currently, in a `PulseSequence` the pulses are ordered by channel and then by start time, I need them ordered by start time so I propose to have them ordered by start time and then channel
* I added a new function called `is_equal` that checks if two pulses are equal but without looking at the start time. This could be useful also for other driver, I think, to avoid to register in memory multiple times the same wavefunction. (Maybe there is a better way to name the function, suggestions are welcomed.)
*  I re-defined the equality operator `==` for all `PulseShape` objects (this is kinda …
> Pulses: change order, check equality

- src/qibolab/designs/channels.py
- src/qibolab/platforms/abstract.py
- src/qibolab/platforms/multiqubit.py
- src/qibolab/platforms/platform.py
- tests/test_platforms_design.py
This PR adds attenuation to the `dummy` platform to be able to tests qibocal protocols which involve attenuation without raising errors. 
@stavros11 maybe there is an easier way to do it. This one seems to work without breaking the other platforms.
Checklist:
> Add attenuation to dummy platform

- src/qibolab/instruments/zhinst.py
Yes, I just moved a line
The only issue is that multiplex this will not work for any frequency sweep as oscillators are limited on the device. But @maxhant for the coupler_Cz_flux_time it manages to get data for both plots. I don't know if it's ok or not.
Checklist:
> Zurich multiplex

- src/qibolab/dummy.py
- src/qibolab/instruments/dummy.py
I was trying to test a two-qubit routine with dummy platform and had some problems with the sweepers (in particular duration sweepers)...
***After*** fixing the sweepers, I realized that for a dummy platform it doesn't make sense to actually do a complex recursion... It's much more faster, shorter and reliable to just generate all the results immediately, not even looking at the sweepers/sequences actual values.
Eventually one could also add some validation at the beginning of the sweep function, to catch eventual errors.
Is there a reason why you decided to do an "actual" sweep?
Checklist:
> Dummy platform sweepers

- src/qibolab/instruments/dummy.py
Fix the way the dummy generates random numbers for Discrimination.
When Singleshot it gets either gets 0 or 1 and when Cylic a float in [0,1].
Checklist:
> Fix Dummy discrimination

- src/qibolab/transpilers/abstract.py
- src/qibolab/transpilers/placer.py
- src/qibolab/transpilers/routing.py
- tests/test_transpilers_abstract.py
- tests/test_transpilers_placer.py
Backpropagation placement defining the number previous gates to be considered
@AleCandido here the parameter is ngates, i you want to use just the first part of a long circuit you can just pass the initial part of the circuit to the placer. In this way the function is general and easy to use.
Checklist:
> Backprop placer

- src/qibolab/transpilers/__init__.py
- src/qibolab/transpilers/placer.py
- tests/test_transpilers_placer.py
Super small PR to change the BackPropagation placer name into "Reverse Traversal Technique", in order to keep the convention purposed in [SABRE's paper](https://arxiv.org/abs/1809.02573).
This follows a discussion had together with @Simone-Bordoni. 
Checklist:
> change Backpropagation name to Reverse Traversal Technique

- src/qibolab/transpilers/unitary_decompositions.py
- tests/test_transpilers_unitary_decompositions.py
There was this TODO in the 2q unitary gate decomposition where sometime the eigenvalues returned where imaginary where they should not be. In some cases (maybe not all) this was due to numpy doing strange things where machine precision was an issue.
I attempt to fix that with a np.round(ut_u, decimals=20). I feel like if at some point we are concerned with gates beyond 20 decimals of precision we will have to deal with other headaches as well. That being said, there might be a more elegant solution to this.
This is sufficient to decompose random 2 qubit Clifford gates, but it might also resolve other problematic matrices.
Checklist:
> Fixed precision issue in 2q unitary gate decomposition

- src/qibolab/__init__.py
- src/qibolab/instruments/abstract.py
- src/qibolab/instruments/dummy.py
- src/qibolab/instruments/qm.py
- src/qibolab/instruments/rfsoc.py
- src/qibolab/instruments/zhinst.py
- src/qibolab/platform.py
- tests/test_platforms_dummy.py
Add sequence unrolling for the dummy to test things in https://github.com/qiboteam/qibocal/pull/398 assuming sequence to be unrolled to be a list of `PulseSequences`.
Tested with the AllXY_unrolling_lists routine using "multiplex".
Checklist:
> Add sequence unrolling for the dummy

- src/qibolab/transpilers/unitary_decompositions.py
I have added a flag to decompose 2 qubit unitaries that  do not generate entanglement into only two single qubit gates. This can be useful as in some cases the decomposition was adding two qubit gates where it didn't need to.
I am using `np.allclose` to check if the numbers are `0`, without any change to `rtol` and `atol`. We could figure out what tolerance we allow. I have also added it to the check for `hz` as in some of the testing I have done, it did not consider `hz` of the order of `10**(-17)` to be 0.
Anyone has experience setting tolerances for this method? 
We can set up special tests for this extra case as well.
Checklist:
> Two qubit gate decomposition without entangling gates

- .github/codecov.yml
It's a tiny maintenance update. Qibolab is hard to test, but waiting for anything better it's just silly the sensible PRs like https://github.com/qiboteam/qibolab/pull/511 are marked with a red cross because of a mild coverage decrease. Essentially, it makes red crosses useless (and green ticks extremely rare).
In principle, we could completely [disable the failure](https://docs.codecov.com/docs/commit-status#if_ci_failed) due to Codecov in Qibolab since we are not really looking at the coverage.
However, for the time being I've just chosen the slimmest approach, trying not to change that much the current status. If it will be again not enough, we could reconsider the options.
Checklist:
> Introduce a threshold for coverage failures

- src/qibolab/qubits.py
This PR adds the Ec, Ej, g and assigment fidelity to the qubit object. These attributes are needed in qibocal for flux flux routines fitting (david/flux_routines_fitting).
Assigment fidelity needed for a webapp tool that I have implemented that shows the qpus/qubits status and latest characterization
Checklist:
> adding Ec, Ej, g and assigment fidelity to the qubit object

- src/qibolab/instruments/zhinst.py
- src/qibolab/platform.py
- tests/test_instruments_zhinst.py
- tests/test_platforms_dummy.py
I broke the way this was working before.
Checklist:
> Fast reset Zurich

- tests/conftest.py
- tests/test_instruments_rfsoc.py
- tests/test_platform.py
QPU tests are passing with QM (qw25q), qblox (qw5q_gold) and now RFSoC (on tii1q_b1):
```sh
srun -p tii1q_b1 pytest -m qpu --no-cov --platform tii1q_b1
```
(requires the `QIBOLAB_PLATFORMS` environment variable properly set)
Checklist:
> Fix RFSoC QPU tests

- src/qibolab/dummy.py
This PR adds a TWPA to the `dummy` platform.
This is necessary to test new incoming protocols in qibocal.
Checklist:
> Add TWPA to dummy platform

- doc/source/tutorials/lab.rst
- src/qibolab/instruments/abstract.py
- src/qibolab/instruments/erasynth.py
- src/qibolab/instruments/oscillator.py
- src/qibolab/instruments/qm/simulator.py
- src/qibolab/instruments/rfsoc/convert.py
- src/qibolab/instruments/rohde_schwarz.py
- src/qibolab/instruments/zhinst.py
- src/qibolab/serialize.py
- tests/dummy_qrc/qblox.py
- tests/dummy_qrc/qblox.yml
- tests/dummy_qrc/qm.py
- tests/dummy_qrc/qm.yml
- tests/dummy_qrc/rfsoc.py
- tests/dummy_qrc/rfsoc.yml
- tests/dummy_qrc/zurich.py
- tests/dummy_qrc/zurich.yml
- tests/test_instruments_rfsoc.py
- tests/test_platform.py
Fix #576. Needed for qibocal routines that update instrument (not qubit) parameters, such as the TWPA calibration. It is also useful to dump some instrument settings (LO frequency, etc.) in the runcard so that we can keep them in record. qibolab_platforms_qrc also needs to be updated for this to work.
@rodolfocarobene can you please confirm that my change in
https://github.com/qiboteam/qibolab/blob/f896cc2dd13890dc40e758281ce05bb182f88fc5/src/qibolab/instruments/rfsoc/convert.py#L39
is okay?
Checklist:
> Instruments section in runcard

- doc/source/getting-started/experiment.rst
Hello!
I was trying to prepare a windows environment to use Qibolab and I noticed that the `export` command behaves a bit differently there.
I changed the tutorial accordingly. 
Checklist:
> Set platform-variable in windows

- src/qibolab/dummy.yml
- src/qibolab/qubits.py
This PR adds a `fidelity` argument to qubit and it also fixes the a typo `assigment_fidelity` -> `assignment_fidelity`.
I spotted this errors while working on qiboteam/qibocal#548.
I will open also a PR in qibolab_platform_qrc.
Checklist:
> Add fidelity to qubit and fix typo

- poetry.lock
- pyproject.toml
Closes qiboteam/qibocal#457 by using the same numpy version in both qibolab and qibocal (1.24.0).
Checklist:
> Fix numpy to 1.24

- src/qibolab/dummy.yml
- src/qibolab/qubits.py
- tests/test_platform.py
After discussing with @andrea-pasquale, we decided to remove them, since this classifiers feature is not used and worsen platform runcard readibility. https://github.com/qiboteam/qibocal/pull/543#discussion_r1369776945
Checklist:
> remove classifiers hpars

- src/qibolab/backends.py
- src/qibolab/platform.py
- tests/test_backends.py
- tests/test_instruments_qmsim.py
Extending qiboteam/qibo#1046 to hardware using the sequence unrolling implemented in #618. Hopefully this can be used to speed up randomized benchmarking.
Checklist:
> Execute circuits with unrolling

- poetry.lock
- pyproject.toml
- src/qibolab/platform.py
Updates the lock to fix https://github.com/qiboteam/qibolab_platforms_qrc/pull/78#issuecomment-1792188639 and also fixes a bug introduced when changing `platform.couplers` from `None` to empty `dict`.
Checklist:
> Update lock and bug fix

- src/qibolab/instruments/rfsoc/driver.py
I think that something broke in the driver after merging #645.
This is a fix purely at the software level. I tried to test it on hardware and now I don't get complains from the driver but only a `Connection refused` error so the fix seems to work. It still needs to be tested on hardware.
Checklist:
> Fix problems with RFSoC driver after adding couplers

- src/qibolab/instruments/zhinst.py
Fixed the start of the measurement pulse and improved code readability.
Checklist:
> Improved code for selection of measurement start

- src/qibolab/instruments/qblox/controller.py
This PR fix the problem the error reported by @andrea-pasquale in issue https://github.com/qiboteam/qibolab/issues/637 about Rabi lenght and Rabi amplitude (probability).
The report can be found here: http://login.qrccluster.com:9000/0w6uZuWgRomTy5wS3QYeMA==
I'm not sure if it will fix also the problems observed by @stavros11 about the cryoscope routine.
Closes #637 
Checklist:
> Fix Rabi probability qblox

- src/qibolab/instruments/qblox/cluster_qcm_bb.py
- src/qibolab/instruments/qblox/cluster_qcm_rf.py
- src/qibolab/instruments/qblox/cluster_qrm_rf.py
- src/qibolab/instruments/qblox/controller.py
- src/qibolab/instruments/qblox/port.py
- src/qibolab/serialize.py
- tests/dummy_qrc/qblox.py
- tests/dummy_qrc/qblox.yml
- tests/qblox_fixtures.py
- tests/test_instruments_qblox_cluster_qcm_bb.py
- tests/test_instruments_qblox_cluster_qcm_rf.py
- tests/test_instruments_qblox_cluster_qrm_rf.py
This modifications have reproduced the basic calibration routine but further testing is needed
> Simplify and move Qblox modules settings

- src/qibolab/instruments/qblox/cluster.py
- src/qibolab/instruments/qblox/cluster_qcm_bb.py
- src/qibolab/instruments/qblox/cluster_qcm_rf.py
- src/qibolab/instruments/qblox/cluster_qrm_rf.py
- src/qibolab/instruments/qblox/controller.py
- src/qibolab/instruments/qblox/port.py
- tests/dummy_qrc/qblox.py
- tests/dummy_qrc/qblox.yml
- tests/qblox_fixtures.py
- tests/test_instruments_qblox_cluster_qcm_bb.py
- tests/test_instruments_qblox_cluster_qcm_rf.py
- tests/test_instruments_qblox_cluster_qrm_rf.py
This fixes qblox tests on qpu.
Here is the report of the qubit spectroscopy (that involves all the three qblox modules) performed with this branch:
http://login.qrccluster.com:9000/tAITAr7YSu-Zz3f6pRfdnQ==
Checklist:
> Qblox setting

- src/qibolab/instruments/dummy.py
- src/qibolab/instruments/qblox/controller.py
- src/qibolab/instruments/zhinst.py
- tests/test_result_shapes.py
Fixes #647 for qblox and adds qpu tests that check that the shapes are correct for each acquisition type (except raw) and averaging mode.
I would also like to fix the shapes for Zurich and also do a quick test with qibocal before merging.
Checklist:
> Add tests for result shapes

- src/qibolab/instruments/qblox/cluster_qcm_bb.py
This small PR allow to use a chip connected to Qblox even if not all the flux channels are physically connected (as happens in https://github.com/qiboteam/qibolab_platforms_qrc/pull/94 for spinq10q).
Checklist:
> Add empty flux `Channels` compatibility

- poetry.lock
- pyproject.toml
- src/qibolab/instruments/zhinst.py
update laboneq dependancy to 2.21.0
Checklist:
> update laboneq dependancy

- src/qibolab/instruments/qblox/controller.py
`Pulse._if` was assigned in `_execute_pulse_sequence` of the controller but never actually used anywhere, so I just dropped it.
Checklist:
> Drop `pulse._if` dependence in Qblox

- src/qibolab/dummy.yml
- src/qibolab/qubits.py
Required by https://github.com/qiboteam/qibocal/pull/684.
When it will get merged I will also update accordingly qibolab_platforms.
Checklist:
> Introduce crosstalk_matrix as `Qubit` attribute

- .github/workflows/publish.yml
- .github/workflows/rules.yml
- README.md
I've fixed the `tests` badge and I've also added others badges.
We can even drop some of them I just wanted to make the `README` look nicer.
I could also propagate some of those changes to the other repos.
Checklist:
> Fix and add new README badges

- doc/source/tutorials/circuits.rst
In this example `qibo` is accessed directly in
```
qibo.set_backend("qibolab", "dummy")
```
therefore an import of `qibo` is needed.
Checklist:
> Fix imports in 'slightly more complex circuit'

- src/qibolab/instruments/qblox/cluster_qrm_rf.py
The driver of the qrm_rf is modified so that if the qrm_rf does not receive any readout pulses, it does not trigger any acquisitions, allowing the use of the module for drive only.
The cluster connected to tii1q_d28 has 2 qrm_rf modules, due to the lack of acm_rf modules.
Checklist:
> Modify qrm_rf driver so that qrm_rf modules can be used as qcm_rf to generate drive pulses.

- src/qibolab/compilers/compiler.py
- src/qibolab/compilers/default.py
- tests/test_compilers_default.py
Closes #551.
Adding rule for implementing GPI gate as R(pi) gate with arbitrary azimuthal angle.
I believe that I don't need to do anything in Qibo, right?
Checklist:
> Add rule for GPI gate

- src/qibolab/instruments/zhinst.py
> Remove offsets_off() method from Zurich class

- poetry.lock
- pyproject.toml
I was looking to update `qibo` to the latest version in `qibocal` but I saw that there was a dependency issue regarding `numpy` caused by the fact that in qibolab `numpy` was fixed to `1.24` when `qibocal` was supporting numba which is not the case anymore. 
If needed I can also update `qibo` to the new release in this PR.
Checklist:
> Remove bound to numpy 1.24

- src/qibolab/instruments/qblox/controller.py
- tests/test_instruments_qblox_controller.py
Fixes https://github.com/qiboteam/qibolab/issues/830
When the number of bins (`nshots * total_number_of_sweep_points`) is larger than the maximum supported by the instrument (`2**17`), the execution is done in batches. Previously the `_sweep_recursion` was called which resulted into infinite recursion stack.
Checklist:
> Qblox recursion fix

- src/qibolab/backends.py
- src/qibolab/instruments/erasynth.py
- src/qibolab/instruments/rohde_schwarz.py
This PR addresses two small issues related to the usage of local oscillators when executing circuits (using the `QibolabBackend`).
First, I get a weird exception warning from qblox after executing a circuit on a platform that contains a Rohde Scharz LO (in my case the qw5q_platinum platform from qiboteam/qibolab_platforms_qrc#125). I didn't copy the exact thing but should be easy to reproduce by running any circuit, ie
```py
from qibo import Circuit, gates
from qibolab.backends import QibolabBackend
c = Circuit(5)
c.add(gates.GPI2(3, theta=0)) # using qubit 3 because it is calibrated
c.add(gates.M(3))
backend = QibolabBackend("qw5q_platinum")
result = backend.execute_circuit(c, nshots=1000)
```
This issue is fixed by removing the `__del__` methods from the LO drivers. I don't think these …
> Disconnect after circuit execution

- src/qibolab/platform.py
- tests/test_platform.py
While testing https://github.com/qiboteam/qibocal/pull/689 I noticed that the platform's helper methods for creating drag pulses were broken (I was the one who implemented them...). This PR fixes the issue.
Checklist:
> Fix drag pulse helper method

- src/qibolab/instruments/zhinst.py
- src/qibolab/instruments/zhinst/__init__.py
- src/qibolab/instruments/zhinst/executor.py
- src/qibolab/instruments/zhinst/pulse.py
- src/qibolab/instruments/zhinst/sweep.py
- src/qibolab/instruments/zhinst/util.py
- tests/dummy_qrc/zurich/platform.py
- tests/test_instruments_zhinst.py
The ZI driver code is unnecessarily complicated and entangled, which makes it very fragile, hard to read and change, easy to introduce bugs. This PR is an attempt to untangle and simplify the code.
What is changed:
- Most of the logic related to analyzing sweeps and deciding how to handle them is extracted into the `ProcessedSweeps` class, and the `classify_sweepers` function. This removes a lot of repetitive code scattered throughout the driver code, plus makes code more linear and easy to follow.
- The functionality of the classes `ZhPulse`, `ZhSweeper`, and `ZhSweeperLine` are combined into one. That lucky one is the `ZhPulse`. The other two are removed.
- Splitting a sequence into subsequences is unified in one place. Previously, for each experiment signal the splitting would happen …
> Clear some clutter in the ZI driver

- poetry.lock
- pyproject.toml
A new qm-qua version (1.1.7) was released which seems to cause an issue. I am not sure if this is driver or firmware related, I will investigate when the instrument is available.
@andrea-pasquale @Edoardo-Pedicillo this should fix #844.
> Fix qm-qua version to 1.1.6

- src/qibolab/instruments/zhinst/executor.py
Historically, the ZI driver was designed so that it splits incoming pulse sequence based on the locations of measurement. This was motivated by some limitations in laboneq, (at least) part of which no longer exist. Eventually the driver will be rewritten to remove the assumptions related to this logic, but for now to make [this](https://github.com/qiboteam/qibocal/pull/691) experiment work, this PR implements a hotfix.
See also discussion in https://github.com/qiboteam/qibolab/issues/840
Tested for qubit 1 with https://github.com/qiboteam/qibocal/pull/691 and https://github.com/qiboteam/qibolab_platforms_qrc/pull/126 (but updated the power range of flux lines from 9 to 1).
Qubit flux dependence:
Resonator flux dependence:
P.S. The amplitude sweeps are indeed flux pulse amplitude sweeps. …
> Hotfix: Exclude flux pulses from subsection splitting logic if they overlap (in time) with readout

- src/qibolab/instruments/zhinst/executor.py
Currently, the ZI driver may change the order of real-time sweepers in certain situations. This was most probably historically done for the following two reasons:
1. hardware limitation(s)
2. optimization of runtime (frequency sweep is considered to be slow, so it is moved to the outer loop, so it changes the least amount of time)
Recently, we discovered that (and confirmed by laboneq developers), that point 1 does not exist. As for point 2, with @Jacfomg we observed that order of real-time sweeps may affect the quality of acquired data (for physical reasons, and not specific to instrument). In light of this it seems that the better decision is that the driver not change the order of sweeps. It is better to let qibocal decide which order works best for which experiment.
Below is output …
> Do not rearrange real-time sweepers (ZI)

- src/qibolab/instruments/zhinst/executor.py
https://github.com/qiboteam/qibolab/pull/848 introduced the section for unsplit channels, but it would face issues if a single experiment applies long flux pulses on multiple places (e.g. on qubit and coupler flux channels). The issue being the non-uniqueness of the section name. All unsplit channels should just constitute a single section. Additionally, the pulse start time is accounted for as well, although there is no known use case for it.
Checklist:
> Fix the hotfix: Single unsplit section

- src/qibolab/instruments/qm/config.py
- src/qibolab/instruments/qm/ports.py
- tests/test_instruments_qm.py
We found that using the `always_on` mode leaves the LOs on even after execution. This may cause issues related to LO leakage, if the mixers are not calibrated and the LO gain is very high.
Using the `triggered` mode allows the LO signal to pass only when something is playing in the corresponding port, by sending a simultaneous digital trigger.
I have done some quick tests with qw5q_platinum and this seems to maintain results. I have not confirmed whether the LOs are really turned off.
> Use triggered mode for QM local oscillators

- src/qibolab/pulses.py
- tests/test_pulses.py
Fixes #826. We were originally planning to postpone this to 0.2, where it is automatically fixed, however since it is relevant for some experiments done now (see https://github.com/qiboteam/qibocal/pull/689#issuecomment-2041002106) and the fix was easy, it would be good to merge it now.
I repeated the experiments from https://github.com/qiboteam/qibocal/pull/689#pullrequestreview-1982457594 using Sergi's runcards from the reports uploaded in that comment before and after DRAG calibration. Here are my reports after the sign correction:
Before: http://login.qrccluster.com:9000/2LXRRtnlTV-dnJXpxoN7BQ==
After: http://login.qrccluster.com:9000/Ov8k7evxSfuy7GburXvBiQ==
The difference is small, but I believe DRAG now works more consistently over all qubits (in contrast to before that was only …
> Hotfix for minus sign in DRAG shape

- poetry.lock
- pyproject.toml
- src/qibolab/instruments/qblox/cluster_qcm_bb.py
- src/qibolab/instruments/qblox/cluster_qcm_rf.py
- src/qibolab/instruments/qblox/cluster_qrm_rf.py
As a side effect of investigating https://github.com/qiboteam/qibolab/issues/845 I had to upgrade the firmware on the instruments in our lab, which in turn means updating the `qblox-instruments` dependency. This PR contains only changes related to this upgrade.
P.S. This upgrade does not fix the issue. The fix is expected to come with another firmware upgrade in future.
Checklist:
> Upgrade qblox-instruments dependency

- src/qibolab/pulses.py
Thanks @sorewachigauyo for reporting this. It would be could if someone else can confirm this is correct because I am not 100% sure.
> Bug(?) in q-component of DRAG pulse

- src/qibolab/dummy/parameters.json
- src/qibolab/pulses/pulse.py
- src/qibolab/serialize.py
- tests/dummy_qrc/qblox/parameters.json
- tests/dummy_qrc/qm/parameters.json
- tests/dummy_qrc/qm_octave/parameters.json
- tests/dummy_qrc/zurich/parameters.json
Addresses https://github.com/qiboteam/qibolab/pull/870#discussion_r1576109435.
Of course the platforms in qibolab_platforms_qrc also need to be updated, but these are already broken in 0.2 for other reasons, so I wouldn't bother for now. We will update them anyway when 0.2 is ready.
> Remove `FluxPulse` from serialization PR

- doc/source/main-documentation/qibolab.rst
- doc/source/tutorials/circuits.rst
- doc/source/tutorials/compiler.rst
- src/qibolab/backends.py
> Remove transpilation hook

- src/qibolab/result.py
- tests/test_result.py
Required by https://github.com/qiboteam/qibocal/pull/832
This PR "corrects" the `average` property of `AveragedIntegratedResults` by returning the object itself without performing the average again.
I've also added the property `phase_std` which is useful for qibocal (if you think that it is not necessary I can always drop it and do it directly in qibocal).
I'm keeping it as draft to account for any possible changes in https://github.com/qiboteam/qibocal/pull/832
EDIT: I've also implemented #897 here.
Checklist:
> Minor adjustments in result objects

- src/qibolab/instruments/zhinst/executor.py
Processed sweeps uses frequency from characterization section. This leads to inconsistency when user updates the frequency of native pulse, but does not update the characterization section (e.g. readout_frequency). This change fixes this inconsistency.  
All of this is being removed for 0.2 release (https://github.com/qiboteam/qibolab/pull/885). This fix is needed for short term, before the realease.
Checklist:
> Collect frequencies before processing sweeps

- src/qibolab/instruments/qm/acquisition.py
I think this is needed to see the time of flight.
> Fix for TOF routine on QM

- src/qibolab/instruments/qm/config.py
- src/qibolab/instruments/qm/controller.py
- tests/test_instruments_qm.py
Fixes https://github.com/qiboteam/qibolab/pull/905#discussion_r1611819168 and https://github.com/qiboteam/qibolab/pull/905#discussion_r1613546747. The second is minor and should not have effects on execution, however the first should affect the case where multiple frequencies are used on the same qubit for readout, which probably doesn't work correctly in the previous implementation.
> Fixes late comments on #905

- src/qibolab/instruments/emulator/pulse_simulator.py
- tests/test_emulator.py
As discussed in the Qibo meeting, I have added the option to use `IntegratedResults` from the results so that we can run other Qibocal routines. I have done some testing for T1 sequences, but because of the sampling rate boost, it takes a long while to complete.
Checklist:
> Add emulator support for fake integrated acquisition

- flake.nix
- src/qibolab/__init__.py
- src/qibolab/backends.py
- src/qibolab/instruments/dummy.py
- src/qibolab/instruments/rfsoc/convert.py
- src/qibolab/instruments/rfsoc/driver.py
- src/qibolab/platform/__init__.py
- src/qibolab/platform/load.py
- src/qibolab/platform/platform.py
- src/qibolab/serialize.py
- src/qibolab/version.py
- tests/conftest.py
- tests/test_instruments_rfsoc.py
- tests/test_platform.py
- tests/test_sweeper.py
This is mainly an extension of the platform loading feature that I had in mind since long (i.e. just treat `$QIBOLAB_PLATFORMS` as most of the other `$PATH`-like variables, with multiple paths and fallback).
I started implementing this as a service for #849, to have both `dummy_qrc` and `emulators` in scope. However, I doubt it will be useful there, since I will just implement a separate fixture for that (though I could convert `dummy_qrc` to a more generic `platforms` fixture, up for voting).
In the process, I started narrowing the exports of Qibolab, since I was already touching `__init__.py`. More or less going in the direction of #790.
Ok, this is usually not a great idea, and I'm already kind of regretting...
I hope that is not breaking anything (things not listed in `__all__` are …
> Add support for multiple platform paths

- flake.nix
- src/qibolab/instruments/emulator/pulse_simulator.py
- tests/test_emulator.py
The just merged #849 was based on a previous version of `main`, and it haven't been updated recently.
Because of this, it was prone to a recent change denying re-exports for objects defined somewhere else (in particular, `Qubit` and `Coupler` objects are not the defined in `qibolab.platform`, but in their own modules).
More tests may have to be fixed.
> Fix emulator imports

- src/qibolab/instruments/rfsoc/convert.py
- src/qibolab/instruments/rfsoc/driver.py
- tests/test_instruments_rfsoc.py
Closes #913. The patch is quite ugly, moreover I am not sure if it works for every case... I've tested it only for a single qubit sweep (readout frequency).
I guess at some point it was introduced that the results must be squeezed like for dummy:
https://github.com/qiboteam/qibolab/blob/2e6c082e5cfada71f95699e3ea67aca13c12d8d1/src/qibolab/instruments/dummy.py#L130-L134
I was instead always returning values in the form of `[[val1, val2, val3, val4...]]` (not sure why, maybe it was wrong from the beginning). However, downgrading qibolab at my last commit and qibocal at 0.0.8 "solves" the issue, so maybe something was introduced in the middle? Do you, @stavros11, @alecandido , @hay-k, recall something specific?
Moreover, are there plans to introduce again some automatic tests with …
> Patch RFSoC result shape

- src/qibolab/serialize.py
Removes the annoying `\"` from qubit names when they are strings in the parameters.json. Also, the loading/dumping is now consistent for platforms with string qubit names and therefore we can copy new_platform parameters produced from qibocal.
> Fix loading of string qubit names

- src/qibolab/unrolling.py
This should be slightly more accurate than the former, since the rectangular pulses should all weight the same, not just the readout ones (and even readout pulses could require samples, if they are non-rectangular).
It is still incredibly rough for a lot of reasons, but the main one could even be that we're using the duration in ns, disregarding the sampling rate.
> Change waveform memory estimation

- src/qibolab/compilers/default.py
The virtual phases were not properly updated when executing circuits containing strings.
Thanks @stavros11 for spotting the issue.
Checklist:
> Fixing compiler rules when dealing with qubit strings

- src/qibolab/couplers.py
- src/qibolab/instruments/abstract.py
- src/qibolab/instruments/emulator/engines/generic.py
- src/qibolab/instruments/emulator/engines/qutip_engine.py
- src/qibolab/instruments/emulator/pulse_simulator.py
- src/qibolab/instruments/icarusqfpga.py
- src/qibolab/instruments/qblox/acquisition.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/devices.py
- src/qibolab/instruments/qm/ports.py
- src/qibolab/instruments/qm/sequence.py
- src/qibolab/platform/platform.py
- src/qibolab/qubits.py
- src/qibolab/serialize.py
This is a migration we could have done at any time, since we have dropped support for py3.8
> Remove usage typing classes in favor of builtins

- poetry.lock
- pyproject.toml
Closes #961 
It was easier to do it immediately, instead of leaving a further issue open and forget.
> TWPA extra

- doc/source/main-documentation/qibolab.rst
- doc/source/tutorials/lab.rst
- doc/source/tutorials/pulses.rst
- src/qibolab/dummy/parameters.json
- src/qibolab/instruments/emulator/pulse_simulator.py
- src/qibolab/instruments/icarusqfpga.py
- src/qibolab/instruments/qblox/cluster_qcm_bb.py
- src/qibolab/instruments/qblox/cluster_qcm_rf.py
- src/qibolab/instruments/qblox/cluster_qrm_rf.py
- src/qibolab/instruments/qblox/controller.py
- src/qibolab/instruments/qblox/sequencer.py
- src/qibolab/instruments/rfsoc/driver.py
- src/qibolab/instruments/zhinst/pulse.py
- src/qibolab/instruments/zhinst/sweep.py
- src/qibolab/pulses/__init__.py
- src/qibolab/pulses/pulse.py
- src/qibolab/pulses/sequence.py
- src/qibolab/serialize.py
- tests/dummy_qrc/zurich/parameters.json
- tests/pulses/test_envelope.py
- tests/pulses/test_plot.py
- tests/pulses/test_pulse.py
- tests/pulses/test_sequence.py
- tests/test_dummy.py
- tests/test_instruments_qblox_controller.py
- tests/test_instruments_qm.py
- tests/test_instruments_rfsoc.py
- tests/test_instruments_zhinst.py
- tests/test_platform.py
- tests/test_unrolling.py
The current layout is a bit suboptimal, because I'm relying on the convention of the probe channel containing `"probe"` in its name in the sequence, and no one else doing it. But channel names in sequences are arbitrary.
Maybe we should stop using strings, and use a `tuple[QubitId, ChannelType]`.
(yes, it seems like we're removing something from one side, `PulseType`, to reintroduce from another, `ChannelType` - but we already have channel types, they are the `Qubit` attributes, which should somehow match the arbitrary strings in the `PulseSequence`, but they are not really forced to...)
> Drop `PulseType`

- src/qibolab/compilers/compiler.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/program/instructions.py
Updates QM driver to work with the `PulseSequence` layout introduced in #965. Resonator spectroscopy, single shot classification and Rabi routines work.
> Update QM driver for new sequence layout

- src/qibolab/qubits.py
- tests/test_instruments_rfsoc.py
Following what was discussed earlier, to avoid errors when attempting discrimination on a platform for which the classification parameters have not been calibrated. Now instead of errors, it will just return random shots.
> Set default threshold to 0

- doc/source/getting-started/experiment.rst
- doc/source/main-documentation/qibolab.rst
- doc/source/tutorials/calibration.rst
- doc/source/tutorials/compiler.rst
- doc/source/tutorials/lab.rst
- src/qibolab/compilers/compiler.py
- src/qibolab/compilers/default.py
- src/qibolab/dummy/platform.py
- src/qibolab/parameters.py
- src/qibolab/platform/platform.py
- src/qibolab/qubits.py
- src/qibolab/sweeper.py
- tests/conftest.py
- tests/test_backends.py
- tests/test_compilers_default.py
- tests/test_dummy.py
- tests/test_platform.py
> Separate channels from natives

- src/qibolab/instruments/qm/components/configs.py
- src/qibolab/instruments/qm/config/config.py
- src/qibolab/instruments/qm/config/devices.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/serialize.py
These updates in the QM driver were required to be compatible with the new serialization. This is based on #983 and the single shot routine has been tested to work on the platform in https://github.com/qiboteam/qibolab_platforms_qrc/pull/153.
The main issue was that `asdict` from `dataclasses` does not seem to work as expected for pydantic `Model` objects, so I had to do a small patch. This may be fixed if we replace all the objects used for QM config to pydantic, but I don't plan to do this for 0.2 as it is fully internal.
> QM driver patches for new serialization

- src/qibolab/instruments/zhinst/executor.py
Fixes the issue described [here](https://github.com/qiboteam/qibolab_platforms_qrc/pull/167#issuecomment-2301498575)
Previously, when qubit kernels were available, the calculated weight was not stored in the `weights` dict, hence when needed it was recalculated, resulting into different laboneq pulse objects (even though the contained data was exactly the same, the IDs of the objects were different), causing the mentioned issue.
> fix kernel based weights being generated multiple times

- src/qibolab/compilers/compiler.py
- src/qibolab/platform/platform.py
- src/qibolab/qubits.py
- tests/test_compilers_default.py
Closes #976 
I implemented the automated padding on the drive channel. Currently, it's undocumented.
However, we should maybe dedicate some more efforts to the compiler, and my proposal is (for the time being) to not even make it part of the public API (cf. #790).
So, this should correspond to the expected behavior, and the former one was classifiable as a bug. Thus, we could say the compiler knows what to do, but (for the time being) how it is doing that is an internal detail.
As soon as we'll take the time to review it (with no rush), we could decide to publicly expose, and properly document what is doing.
> Two qubit alignment

- .github/workflows/deploy.yml
- .github/workflows/rules.yml
- doc/source/conf.py
- doc/source/index.rst
- flake.lock
- poetry.lock
- pyproject.toml
- src/qibolab/compilers/default.py
- src/qibolab/components/channels.py
- src/qibolab/instruments/abstract.py
- src/qibolab/instruments/bluefors.py
- src/qibolab/instruments/icarusqfpga.py
- src/qibolab/instruments/qblox/module.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/pulses/envelope.py
- src/qibolab/pulses/pulse.py
- src/qibolab/result.py
- src/qibolab/sequence.py
- src/qibolab/unrolling.py
- tests/test_instruments_qm.py
- tests/test_instruments_rfsoc.py
It was blocked until now, mainly because of QUA (and also Qibosoq, but in `qibosoq@main` is already 3.12-ready, we simply did not bother to release).
This was also blocking Qibo releases supporting py3.12, and that's why we didn't catch #988 before.
However, I realized that there was a smarter way: just gate QUA to py<3.12, and not the whole Qibolab.
Closes #988
> Python 3.12 and Qibo > 0.2.6

- .github/workflows/deploy.yml
- .github/workflows/rules.yml
- doc/source/conf.py
- doc/source/index.rst
- flake.lock
- poetry.lock
- pyproject.toml
- src/qibolab/compilers/default.py
- src/qibolab/components/channels.py
- src/qibolab/instruments/abstract.py
- src/qibolab/instruments/bluefors.py
- src/qibolab/instruments/icarusqfpga.py
- src/qibolab/instruments/qblox/module.py
- src/qibolab/instruments/qm/config/config.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/program/instructions.py
- src/qibolab/instruments/qm/program/sweepers.py
- src/qibolab/pulses/envelope.py
- src/qibolab/pulses/pulse.py
- src/qibolab/result.py
- src/qibolab/sequence.py
- src/qibolab/unrolling.py
- tests/test_instruments_qm.py
- tests/test_instruments_rfsoc.py
These are the fixes required to make things work with #970. I based it on #994 since this queue of PRs is also ready. I am not sure if it is the best possible way to fix, but was tested to work with single shot routine and qw11qD. 
Generally, I am not very happy with this change, I think that both the separate acquisition and `ChannelId` make things slightly more complicated. The acquisition part was expected, since it is not natively supported by QM (as far as I know), the `ChannelId` part requires casting to string several times. However, the difference is not that big and we can still live with it.
> Update QM driver to new acquisition and `ChannelId`

- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/program/__init__.py
- src/qibolab/instruments/qm/program/arguments.py
- src/qibolab/instruments/qm/program/instructions.py
- src/qibolab/instruments/qm/program/sweepers.py
- src/qibolab/pulses/__init__.py
- src/qibolab/pulses/plot.py
- src/qibolab/pulses/pulse.py
- src/qibolab/sequence.py
- src/qibolab/sweeper.py
- tests/test_sequence.py
Follows the plan outlined in https://github.com/qiboteam/qibolab/issues/935#issuecomment-2265612540, which I copy here in order to track progress:
- this will have the specific meaning of a runtime synchronization, possibly introducing delays
Example report for the Rabi length routine: http://login.qrccluster.com:9000/3XbCXPG-TAGC5uODkQDGFQ==
There is still an issue at short times (< 30ns) however I believe this is not due to the scheduling, as it appears even when using `qua.align()` and `qua.switch_()` with multiple waveforms. With the 1 clock cycle (=4ns) padding on delays, there is no overlap between the drive and readout pulses, as shown in the following simulation.
<details>
<summary>Simulation plot</summary>
</details>
> QM duration sweeper using multiple waveforms

- src/qibolab/instruments/qm/config/config.py
- src/qibolab/instruments/qm/config/pulses.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/program/arguments.py
- src/qibolab/instruments/qm/program/instructions.py
- src/qibolab/instruments/qm/program/sweepers.py
Essentially support playing and sweeping over durations with 1ns resolution (lifting the 4ns constraint). Also the related discussion in #979 should now be fixed. Here I am doing the "baking" (=padding with zeros) myself, instead of using the QM helpers, because this way it fits better with the rest of the driver.
Here is an example of the Rabi length with 1ns step: http://login.qrccluster.com:9000/EWxzJbXUSwmaT8_ES4pF0g==
This is ready for the most part. I just need to check how it behaves for rectangular pulses, but I need to write a script to do this.
> Add baking in QM driver

- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/program/instructions.py
- src/qibolab/platform/__init__.py
- src/qibolab/platform/platform.py
- src/qibolab/unrolling.py
- tests/test_platform.py
- tests/test_unrolling.py
Implements the missing features needed to close #969.
Unrolling was tested with the single shot routine and it's working, except the fact that the result shape remains a bit weird, similarly to 0.1 (see [f4b776978180f3ef71a093d4c3c0f6ce612da358](https://github.com/qiboteam/qibocal/pull/809/commits/f4b776978180f3ef71a093d4c3c0f6ce612da358)). I am not sure if #964 is aiming to improve on this.
Parallel sweeps are implemented but not tested, as they are not used in any existing routine. I only confirmed that they don't break non-parallel sweeps. We need to write a custom script to test them, but I will probably do so after dropping sweeper types (which will force us to use them anyway).
> Unrolling and parallel sweeps for QM

- doc/source/getting-started/experiment.rst
- doc/source/main-documentation/qibolab.rst
- doc/source/tutorials/calibration.rst
- src/qibolab/components/configs.py
- src/qibolab/identifier.py
- src/qibolab/instruments/qm/components/configs.py
- src/qibolab/parameters.py
- src/qibolab/platform/platform.py
- src/qibolab/qubits.py
- src/qibolab/sequence.py
- src/qibolab/serialize.py
- src/qibolab/sweeper.py
- src/qibolab/unrolling.py
- tests/test_parameters.py
Closes #990 
https://github.com/qiboteam/qibolab/blob/b0ba6e47afbea8dfe0f181001d4518d015f1c708/src/qibolab/serialize.py#L61
- ~~allow original QM objects, partially reverting https://github.com/qiboteam/qibolab/pull/989/files~~
- postponed to #1001
> Extend `Config` beyond channels

- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/program/arguments.py
- src/qibolab/instruments/qm/program/instructions.py
- src/qibolab/instruments/qm/program/sweepers.py
- src/qibolab/sweeper.py
- tests/conftest.py
- tests/test_sweeper.py
Following the discussion in #540, this PR makes all QM sweepers absolute. Since `SweeperType` is already dropped in 0.2, this will also close the issue. 
I tested on hardware with the Rabi routine using an absolute amplitude sweeper: http://login.qrccluster.com:9000/XftyLYqDSsG8xBCkcz6ibg==
In this case, the same amplitude range is used on all qubits. It is possible to use a different range per qubit using parallel sweepers (#1008), but I have not tested this.
@alecandido @andrea-pasquale note that although all amplitude sweepers are now absolute (no more factors and multiplications), flux pulses are always played on top of the DC offset (sweetspot). This is true even when not sweeping. Therefore, amplitude sweeps on flux pulses will also be played on top of the DC offset. I could change …
> Convert all QM sweepers to absolute

- doc/source/getting-started/experiment.rst
- doc/source/tutorials/calibration.rst
- src/qibolab/backends.py
- src/qibolab/compilers/compiler.py
- src/qibolab/native.py
- src/qibolab/platform/platform.py
- src/qibolab/pulses/__init__.py
- src/qibolab/pulses/pulse.py
- src/qibolab/result.py
- tests/conftest.py
- tests/test_dummy.py
- tests/test_native.py
- tests/test_platform.py
> Results collection

- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/program/arguments.py
- src/qibolab/instruments/qm/program/instructions.py
- src/qibolab/instruments/qm/program/sweepers.py
I tested the resonator spectroscopy on hardware and unfortunately I had to refactor again the QM sweeper to make it work. There were basically two issues:
1. The frequency sweeper is defined on probe channels, since these are the ones containing the `"frequency"` attribute in our parameters.json. However, due to the usual QM issue we need to translate this to a sweeper on the acquisition channel when writing the QUA program.
2. QUA seems to not like large numbers, even when defined as integers (?). It was giving me a weird error:
```py
2024-09-03 09:46:55,152 - qm - INFO     - Sending program to QOP for compilation
2024-09-03 09:46:55,284 - qm - ERROR    - Internal error: java.lang.IllegalStateException: given number cannot be presented by QUA int representation
at …
```
> fix: refactor QM frequency sweeper for resonator spectroscopy to work

- src/qibolab/backends.py
- src/qibolab/instruments/abstract.py
- src/qibolab/instruments/bluefors.py
- src/qibolab/instruments/oscillator.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/zhinst/executor.py
- tests/instruments/test_bluefors.py
- tests/instruments/test_erasynth.py
- tests/instruments/test_oscillator.py
- tests/instruments/test_rohde_schwarz.py
I think it is redundant, as for most instruments there are different ways to check if they are connected, such as `if self.device is not None`. If it is needed for some instrument, we can have an internal private variable (`_is_connected`).
I left `is_connected` in the platform, however in principle we could convert it to a propery and query the instruments if they are connected. That would require re-implementing `is_connected` to the instruments as a public property.
> Drop `is_connected` from instruments

- doc/source/main-documentation/qibolab.rst
- src/qibolab/dummy/parameters.json
- src/qibolab/dummy/platform.py
- src/qibolab/qubits.py
- tests/test_compilers_default.py
Closes #1022. Originally planned for 0.2.1, I just implemented it because it was easy and is expected to simplify platform creation, so it is slightly interface facing (even though it is a new feature).
If we need to delay for some reason, we can keep this open and merge after 0.2.0 is released.
> Qubit creation helpers

- src/qibolab/native.py
- src/qibolab/sequence.py
- tests/integration/test_sequence.py
- tests/test_native.py
- tests/test_sequence.py
> Sequence building

- doc/source/main-documentation/qibolab.rst
- doc/source/tutorials/pulses.rst
- src/qibolab/_core/compilers/default.py
- src/qibolab/_core/native.py
- tests/test_compilers_default.py
- tests/test_native.py
- tests/test_parameters.py
Unfortunately, the `RXY` name is non-standard, but I was lacking a better one.
Any suggestion? @stavros11 @andrea-pasquale 
- ~~restore some validation?~~
> Split RX from RXY

- doc/source/getting-started/experiment.rst
- doc/source/main-documentation/qibolab.rst
- doc/source/tutorials/calibration.rst
- doc/source/tutorials/pulses.rst
- src/qibolab/_core/backends.py
- src/qibolab/_core/execution_parameters.py
- src/qibolab/_core/platform/platform.py
- src/qibolab/_core/sweeper.py
- tests/conftest.py
- tests/integration/test_sequence.py
- tests/test_dummy.py
- tests/test_platform.py
> Make execution parameters private

- doc/source/tutorials/instrument.rst
- src/qibolab/_core/backends.py
- src/qibolab/_core/compilers/compiler.py
- src/qibolab/_core/instruments/abstract.py
- src/qibolab/_core/instruments/qm/program/acquisition.py
- src/qibolab/_core/pulses/pulse.py
- src/qibolab/_core/sweeper.py
- tests/test_platform.py
While checking for `ExecutionParameters`, I found various leftovers, mainly in docstrings, which should have been updated to the new public API (and `_core` structure).
> Fix some docstrings

- src/qibolab/compilers/default.py
I believe that this was the issue which was giving us a weird behavior in the single qubit tomography @stavros11 @alecandido.
If we consider the definition of GPI2 provided by Qibo we have that $GPI2(0) = R_X(\pi/2)$ and $GPI2(\pi /2) = R_Y(\pi/2)$ which means that the GPI2 should have the following representation
$$
GPI2(\phi) = e^{-i \frac{\pi}{2} ( \cos{\phi} X + \sin{\phi} Y)}
$$
We now need to compute how $GPI2(\phi)$ changes when we apply an $R_Z(\tilde \phi)$ gate
$$
R_Z(\tilde \phi) GPI2(\phi) R_Z(- \tilde \phi) = GPI2( \phi^*)
$$
We can find $\phi^*$ with the following passages
$$
R_Z ( \tilde \phi) e^{-i \frac{\pi}{2} ( \cos{\phi} X + \sin{\phi} Y)} R_Z (- \tilde \phi) = e^{-i \frac{\pi}{2} ( \cos{(\phi - \tilde \phi)} X + \sin{(\phi - \tilde \phi)} Y)} =GPI2 (\phi - \tilde …
> Fixing compiler rule

- src/qibolab/_core/dummy/parameters.json
- src/qibolab/_core/unrolling.py
Fixes #1058 (I was very curious so had to check). @alecandido, maybe you can also confirm, but I believe `Bounds.waveforms` should be `float` instead of `int` as it is calculated as a `sum(pulse.duration)` and `pulse.duration` is `float`.
The reason we did not catch this in the tests is because even though `duration` is annotated as `float`, we are only using integer durations in the dummy platform used in tests. Here I changed one of the durations to a float and indeed some tests were failing before the fix.
Also, the reason the second cell from https://github.com/qiboteam/qibolab/issues/1058#issue-2562285032 doesn't raise an error, is that it is using a `Rectangular` shape, which is a special case for the `_waveforms` function. If you change that to `Gaussian` you will still get the …
> Float waveforms

- src/qibolab/_core/instruments/qm/components/configs.py
- src/qibolab/_core/instruments/qm/config/__init__.py
- src/qibolab/_core/instruments/qm/config/config.py
- src/qibolab/_core/instruments/qm/config/devices.py
- src/qibolab/_core/instruments/qm/config/elements.py
- src/qibolab/_core/instruments/qm/config/pulses.py
- src/qibolab/_core/instruments/qm/controller.py
- src/qibolab/_core/instruments/qm/program/acquisition.py
- src/qibolab/_core/instruments/qm/program/arguments.py
- src/qibolab/_core/instruments/qm/program/instructions.py
- src/qibolab/_core/instruments/qm/program/sweepers.py
Ports #1045 to qibolab 0.2.
TODO:
> Support for QM OPX1000 in 0.2

- src/qibolab/instruments/qm/__init__.py
- src/qibolab/instruments/qm/config.py
- src/qibolab/instruments/qm/controller.py
- src/qibolab/instruments/qm/devices.py
- src/qibolab/instruments/qm/ports.py
- src/qibolab/instruments/qm/sweepers.py
There are some errors occuring, particularly when using multiple qubits in parallel, which I have not fully pinpointed yet.
So far I have been able to run some resonator spectroscopy (example http://login.qrccluster.com:9000/5qKIEfDTRHqYx64Y2bOt9g==) and punchout but at maximum 4 qubits simultaneously.
> Add support for OPX1000 in QM driver

- src/qibolab/instruments/qblox/cluster_qcm_bb.py
- src/qibolab/instruments/qblox/cluster_qcm_rf.py
- src/qibolab/instruments/qblox/cluster_qrm_rf.py
- src/qibolab/instruments/qblox/controller.py
- src/qibolab/instruments/qblox/port.py
- src/qibolab/instruments/qblox/sequencer.py
- src/qibolab/platform/platform.py
- src/qibolab/pulses.py
- src/qibolab/result.py
- tests/dummy_qrc/qblox/parameters.json
- tests/dummy_qrc/qblox/platform.py
- tests/test_instruments_qblox_controller.py
- tests/test_pulses.py
- tests/test_result.py
This PR brings the following:
- some cherry picked commits from branch **alvaro/latest_20231215** that collectively
1. introduce support for couplers in the qblox driver.
2. expose `offset_i` and `offset_q` mixer calibration parameters for qblox RF modules.
- cleanup of the said commits to 
1. align the code with main (the commits were based on older version of qibolab)
2. make the code more pythonic and more readable
3. remove things that were done from a perspective of a user that uses qblox alone (i.e. from a perspective where qibolab==qblox driver), but should not be part of things qibolab does.
- fix "deserialization" of `Custom` pulse shape:
- as a side effect fixes deserialization of IIR, and SNR as well.
This is intended to cover the discussions in …
> collection of small fixes, features, and random pieces of code

- .pre-commit-config.yaml
> Fix docformatter conflict w/ pre-commit 4 - 0.2

- .pre-commit-config.yaml
Temporary solution while waiting for https://github.com/PyCQA/docformatter/issues/293
> Fix docformatter conflict w/ pre-commit 4

- src/qibolab/_core/instruments/qm/controller.py
@alecandido I believe we had this discussion before releasing 0.2 and we were expecting that `int` (not `float`) durations will be captured by pydantic, however this does not seem to be the case. This issue appears in some qibocal routines that allow to change pulse durations (eg. qubit spectroscopy), so I am using
```py
pulse = pulse.model_copy(update={"duration": 1000})
```
in the routine and there it seems that I am able to pass `int`s, which then cause the driver to fail. In these cases, the duration is read from the qibocal action runcard, so another fix is to just use floats there (1000.0 instead of 1000). However that's a bit annoying and I wouldn't expect every user to do it, that's why the proposed fix here.
> Handle integer pulse duration in QM

- src/qibolab/backends.py
- tests/test_backends.py
Qibo needs `qubits`, `connectivity`, and `natives` to create a default transpiler.
https://github.com/qiboteam/qibo/blob/65bdfee7f5d30eb1b18cb31e54a28bac5bfd2e1a/src/qibo/backends/abstract.py#L32-L50
For `native_gates`, I returned all the native gates that can be executed on at least one case... (couplers are excluded) Please let me know if there is a better approach.
Checklist:
> Add properties in QibolabBackend

- doc/source/tutorials/compiler.rst
- src/qibolab/backends.py
- src/qibolab/compilers/compiler.py
- src/qibolab/compilers/default.py
- tests/test_backends.py
- tests/test_compilers_default.py
This covers issue #1073.
- `circuit.wire_names` is copied to `Platform.wire_names` each time `execute_circuit(circuit, ...)` is run.
- In `get_qubit(qubit)`, when `qubit` is an integer, it returns the corresponding physical qubit name from `wire_names`.
- In some rules, `get_qubit()` is used to retrieve `QubitId`.
- Test files is updated.
Checklist:
> Use of `wire_names`

- src/qibolab/_core/pulses/envelope.py
Now that `Custom` is all the rage, I noticed there was a leftover related to the type of its attributes, preventing its serialization.
(To be fair, I actually discovered it by chance in the context of https://github.com/qiboteam/qibolab_platforms_qrc/pull/201, only because it is used in the `iqm5q` parameters...)
> Make `Custom` envelope serializable

- src/qibolab/instruments/qm/controller.py
Removes the `self.manager` reference, so that QM is not available after calling `platform.disconnect()`.
Note that in 0.2 this is already fixed: https://github.com/qiboteam/qibolab/blob/13c94d493daf9c5938c44b21589672d6da2dc307/src/qibolab/_core/instruments/qm/controller.py#L239
> Really disconnect QM (0.1)

- src/qibolab/platform/platform.py
Implements the suggestion of #1108 for 0.1, which is what was primarily causing the temperature issues. Note that it will only work when the `Platform` interface is used, not the instruments directly, but this should capture most cases in practice. It may be possible to lower it to the drivers. If you agree, I can also port it to 0.2.
I have tested and it seems that the handler is called successfully on qw11q when sbatch+scancel is used. It also works on dummy for both sbatch+scancel and srun+(Ctrl+C). However, srun+(Ctrl+C) does not seem to work on qw11q and the handler is skipped! I am not sure why.
I have also confirmed that the TWPA pump LO is turned off by the handler, which is not the case now (LO will remain on after job cancellation). I have not confirmed that QM jobs are properly …
> Disconnect platform when job is interrupted

- src/qibolab/compilers/compiler.py
- src/qibolab/dummy/parameters.json
- tests/test_compilers_default.py
- tests/test_dummy.py
Current compiler adds the virtual-z phases to flux pulses in addition to the drive ones. This should not have any effect since flux pulses are DC, but it is probably better to remove to be on the safe side.
@igres26 I have not tested on hardware, but this should remove the frame rotations of the flux channel from the qua script.
> Fix compiler adding phases to flux pulses

- src/qibolab/_core/instruments/qm/controller.py
- src/qibolab/_core/instruments/qm/program/arguments.py
- src/qibolab/_core/instruments/qm/program/instructions.py
Using the Rabi length routine, we noticed that this sweeper works best when we upload the pulse with the minimum duration among the swept values. This is probably due to the inability to compress arbitrary waveforms in real time (see https://docs.quantum-machines.co/latest/docs/Guides/features/?h=interpo#dynamic-pulse-duration).
Using this branch, the Rabi length behaves consistently between 0.1 (http://login.qrccluster.com:9000/MutpaUWhRPa9XlYyhD8mYA==) and 0.2 (http://login.qrccluster.com:9000/xKil3FR_Qv-4El7gQHd3vQ==).
Note that the standard (non-interpolated) sweeper still behaves differently for this experiment, however for that case there is no 0.1 counterpart that we can compare to.
> Fix duration interpolated sweeper for QM

- poetry.lock
- pyproject.toml
- src/qibolab/_core/instruments/qblox/cluster.py
- src/qibolab/_core/instruments/qblox/config.py
- src/qibolab/_core/instruments/qblox/results.py
- src/qibolab/_core/instruments/qblox/sequence/sequence.py
Still draft since I was not able to fully execute yet. I am currently trying the following minimal example:
```py
from qibolab import create_platform
platform = create_platform("iqm5q")
natives = platform.natives.single_qubit[1]
sequence = natives.RX() | natives.MZ()
platform.connect()
result = platform.execute([sequence], nshots=5000)
platform.disconnect()
```
I will also put a comment with the relevant error under every attempted fix.
> Qblox driver fixes for executing on iqm5q

- src/qibolab/_core/pulses/envelope.py
The current definition of the SNZ waveform is wrong given that the waveform is supposed to use negative amplitudes in the second half of the pulse. This PR provides the fix.
> Fixing SNZ waveform

- src/qibolab/_core/instruments/qm/program/instructions.py
- src/qibolab/_core/instruments/qm/program/loops.py
Fixes #1147. 
Originally in #1131 I tried to make my own `from_array` based on qualang_tools, but as noted in #1147 this did not turn out well, so here I decided to port the function as is.
> Port exact `from_array` from qualang_tools

- src/qibolab/instruments/qm/controller.py
> [0.1] Specify QM cluster name

- src/qibolab/_core/instruments/qm/controller.py
Allow specifying the cluster name used in the `QuantumMachinesManager` to support multiple cluster configurations.
*TII note: This is needed to use qw5q_platinum with the second OPX1000 cluster, which is connected to the same router as the first one.
> Specify QM cluster name

- src/qibolab/_core/dummy/platform.py
- tests/dummy_hardware/platform.py
- tests/test_platform.py
Adds test for the fix in #1151.
> Add test for `create_platform` when `Hardware` is used

- src/qibolab/_core/instruments/emulator/emulator.py
- src/qibolab/_core/instruments/emulator/hamiltonians.py
- src/qibolab/_core/instruments/emulator/utils.py
Closes #1170
@andrea-pasquale I'm not sure whether I should aim to do anything more in here.
Just to summarize what it may be possible about integration: currently, I'm just putting the content of discrimination on the I component, supplying a null Q one, and adding some fixed Gaussian noise.
We could add some configurations (alongside channels configs), to perform the following operations:
- scale the noise by a custom $\sigma$
- scale the noise with an array of $\sigma_{\ket{i}}$, according to the discriminated $\ket{i}$ state (it would only apply in single-shot, and averaged for cyclic/sequential averages)
- introduce an angle and threshold, to rotate and translate the entire plane
- introduce an amplification, to scale the whole plane
All of these are just trivial arrays manipulation, …
> Introduce integration acquisition mode for emulator

- src/qibolab/_core/instruments/emulator/emulator.py
- src/qibolab/_core/instruments/emulator/hamiltonians.py
- src/qibolab/_core/instruments/emulator/operators.py
- src/qibolab/_core/instruments/emulator/utils.py
In this PR I generalized the emulator to a $n$-levels transmon system with a driving term
```math
H = \omega_q b^\dagger b + \frac{\alpha}{2} b^\dagger  b^\dagger  b b - i V(t) \epsilon(t)(b - b^\dagger) 
```
I was able to run a qubit spectroscopy between to find the frequency for the $1\rightarrow 2$ transition, assuming a $\omega_q^{01} = 5.0 \ \text{GHz}$ and $\frac{\alpha}{2 \pi} = - 200 \ \text{MHz}$ I was able to correctly measure the transition frequency between $\ket{1} \rightarrow \ket{2}$.
Here on the y axis I am measuring the population of the excited state.
I was able to run a Rabi experiments between state $\ket{1}$ and $\ket{2}.$
Here the y axis is again the population of $\ket{1}$ while the x axis is the drive power.
I've also added dissipation (see Qibocal related PR …
> Generalize emulator to n-levels transmon

- src/qibolab/_core/instruments/emulator/emulator.py
- src/qibolab/_core/instruments/emulator/hamiltonians.py
In the emulator, the acquisitions were isolated from the various expectation values returned, by computing the times at which they were supposed to happen.
This computation was not taking into account the presence of multiple channels, and a single duration was used for all of them
https://github.com/qiboteam/qibolab/blob/599db8a0fcd79d5d9698fb20b9670cbf0a17180d/src/qibolab/_core/instruments/emulator/emulator.py#L167-L175
In practice, it was already working, because the acquisition channels were isolated (checking for the `AcquisitionConfig`) and a single qubit was present. So, in this specific case, a single channel was isolated.
By reworking, such that it acts on each channel separately, the computation is easier (since no access to configs is required) and more general (taking into …
> Generalize acquisitions handling in emulator

- doc/source/main-documentation/qibolab.rst
- src/qibolab/_core/dummy/platform.py
- src/qibolab/_core/parameters.py
- src/qibolab/_core/platform/platform.py
- src/qibolab/_core/qubits.py
~~This PR introduces a `QubitPairMap` type which will be passed to `Platform`.
The motivation behind this is to have the possibility to add channels which are acting on a specific pair, which is the case for the CR gate which we will need at some point.~~
Renaming `drive_qudits` to `drive_extra` and modifying its type to allow to define also cross resonance channels.
> Renaming `drive_qudits` to `drive_extra`

- src/qibolab/_core/instruments/qm/program/instructions.py
- src/qibolab/_core/instruments/qm/program/sweepers.py
- src/qibolab/_core/sweeper.py
- tests/test_sweeper.py
Fixes #1193, by propagating the sweeping of `VirtualZ` to the QM driver.
I also added a new `Parameter.phase` to match the `VirtualZ.phase` attribute. This part is optional, as we could also use the existing `Parameter.relative_phase`, however this would break the symmetry between `Parameter` and `Pulse` attribute names which in all other cases agree. Now `VirtualZ` sweepers need to be defined as
```py
vz = VirtualZ(phase=0)
sweeper = Sweeper(parameter=Parameter.phase, range=..., pulses=[vz])
```
@alecandido (and others) let me know what you think about this point, or if you prefer to drop the `Parameter.phase` and use the existing `Parameter.relative_phase` instead. Note that the duplication between `Pulse.relative_phase` and `VirtualZ.phase` is already known (#1157) but dropping any of …
> Sweep `phase` of `VirtualZ` in QM

- tests/conftest.py
- tests/instruments/emulator/test_circuits.py
Some tests recently merged #1191 are failing in [main](https://github.com/qiboteam/qibolab/actions/runs/14511704298/job/40712017967). I think that the error is caused by the fact that with the `qutrit` platform we could have a few samples outside of the computational basis, which is breaking the result object in Qibo when we are computing probabilities.
As a workaround in the tests I am just using the samples and I verify the the average value is what we should expect.
Eventually we could try to generalize the `.probabilites()` in Qibo to support also states outside the computational basis, even if it will probably be quite painful given that Qibo only support qubits.
> Use samples instead of probabilities in emulator tests

- src/qibolab/_core/pulses/envelope.py
In `main`, the idling time of SNZ is proportional to the number of samples, meaning it adjusts dynamically when sweeping the pulse duration for the Chevron experiment. Together with @Luca-Ben-Herrmann, we tested various pulse parameters but were unable to observe the characteristic Chevron pattern. For example, this [report](http://login.qrccluster.com:9000/NW8L2RmfQjanw-1v8w_ANA==/) shows one of the outputs. Although the [paper](https://arxiv.org/pdf/2008.07411) does not explain the detail of Chevron experiment, it is not clear why the idling time needs to be swept.  
In this branch, the idling time is fixed (absolute), as seen in this [report](http://login.qrccluster.com:9000/_aXKWNYbS86SvszFZZhOKQ==/). Additionally, this PR includes code refactoring to increase readability. …
> Fix SNZ envelope

- src/qibolab/_core/instruments/qm/components/configs.py
- src/qibolab/_core/instruments/qm/config/config.py
- src/qibolab/_core/instruments/qm/config/devices.py
- src/qibolab/_core/instruments/qm/config/elements.py
- src/qibolab/_core/instruments/qm/config/pulses.py
- src/qibolab/_core/instruments/qm/controller.py
Adds support for [MW-FEMs](https://docs.quantum-machines.co/latest/docs/Guides/opx1000_fems/?h=upsampl#microwave-fem-mw-fem) in the QM driver. In TII lab we only have LF-FEMs so we I cannot fully test this. I am only relying on printing the generated `config` and checking whether it complies with the format presented in https://docs.quantum-machines.co/latest/docs/Introduction/config/?h=fem#configuration-components.
Here is an example platform with two flux tunable qubits on a single readout, controlled using MW-FEM for readout and drive and LF-FEM for flux:
<details>
<summary>platform.py</summary>
```py
import pathlib
from qibolab import (
AcquisitionChannel,
ConfigKinds,
DcChannel,
IqChannel,
Platform,
Qubit,
)
from qibolab.instruments.qm import Octave, QmConfigs, QmController
FOLDER = …
```
> Add support for OPX1000 MW-FEMs

- doc/source/main-documentation/qibolab.rst
- doc/source/tutorials/emulator.rst
- src/qibolab/_core/instruments/emulator/emulator.py
- src/qibolab/_core/instruments/emulator/hamiltonians.py
- src/qibolab/_core/instruments/emulator/results.py
- tests/instruments/emulator/platforms/fixed-frequency-qutrits/parameters.json
- tests/instruments/emulator/platforms/fixed-frequency-qutrits/platform.py
- tests/instruments/emulator/platforms/qubit/parameters.json
- tests/instruments/emulator/platforms/qubit/platform.py
- tests/instruments/emulator/platforms/qutrit/parameters.json
- tests/instruments/emulator/platforms/qutrit/platform.py
- tests/instruments/emulator/platforms/split-transmons/parameters.json
- tests/instruments/emulator/platforms/split-transmons/platform.py
- tests/instruments/emulator/test_circuits.py
- tests/instruments/emulator/test_emulator.py
- tests/instruments/emulator/test_hamiltonians.py
- tests/instruments/emulator/test_sequence.py
This PR is a first attempt at introducing flux-tunability to the emulator.
I've coded a prototype to have sweepers for both flux pulses and offset.
TODO:
> Adding flux-tunability in emulator

- src/qibolab/_core/instruments/qm/controller.py
- src/qibolab/_core/instruments/qm/program/instructions.py
We have observed that leaving the DC offsets always on leads to more stable behavior in the two-qubit gate calibration. After a discussion with the QRC lab yesterday, we decided to implement this as the default behavior.
It is still possible to define a platform that switches off the offsets after disconnecting (old behavior), using `QmController(close_qm=True)`. The default behavior will be `close_qm=False` which means offsets always on.
Draft as I would like to check how it works on hardware before merging.
> Leave QM DC offsets on after disconnecting

- src/qibolab/_core/instruments/qblox/q1asm/ast_.py
- src/qibolab/_core/instruments/qblox/sequence/experiment.py
- src/qibolab/_core/instruments/qblox/sequence/loops.py
- src/qibolab/_core/instruments/qblox/sequence/program.py
These fixes were found by comparing the generated q1asm program with the corresponding from 0.1. Now the single shot classification results on iqm5q match with 0.1 for the same parameters:
* 0.1: http://login.qrccluster.com:9000/fE-On1s1S0ujOvYFsxSXNg==
* 0.2 (using this fix): http://login.qrccluster.com:9000/Mx4HWZUSQgaVEtmArGjQ1w==
I have not tested other routines.
> Qblox: Fix single shot routine for iqm5q

- src/qibolab/_core/instruments/qm/controller.py
- src/qibolab/_core/instruments/qm/program/acquisition.py
Checks if all experiment parameters (`configs`, `sequences` and `sweepers`) remain the same with the previous execution and in that case it is using the previous `QuantumMachine` and compiled program to speed-up execution. This is expected to help a bit in cases where exactly the same program needs to be executed multiple times, such as when sweeping the bias of the SPI rack on software or during TWPA pump calibration. For example a flux scan with the SPI that originally took 3mins 37sec dropped to 1min 11sec with the cache:
* Without cache: http://login.qrccluster.com:9000/HmHhwvIRRVucspAf46672w==
* With cache: http://login.qrccluster.com:9000/xzb7VcNcRuul-i3_41UP0A==
It may be possible to improve even further using similar ideas and also I think the code can be improved by reworking a …
> Implement a cache in QM driver to avoid recompiling programs

- src/qibolab/_core/instruments/qblox/config/sequencer.py
- src/qibolab/_core/instruments/qblox/results.py
- src/qibolab/_core/instruments/qblox/sequence/asm.py
- src/qibolab/_core/instruments/qblox/sequence/experiment.py
Fixes the following three issues observed when trying to execute circuits on Qblox:
1. b191950: q1asm error from `set_ph_delta` being used with negative values when trying to execute any gate.
2. 1221a1d: classified (thresholded) results being inaccurate (cherry-picked from #1252)
3. 34e119f: `.frequencies()` calculation from qibo failing.
I have not confirmed the fixes work on hardware (verifying the actual results), however they fix the errors when running on a qblox cluster not connected to QPU (particularly the `qblox-test` from https://github.com/qiboteam/qibolab_platforms_qrc/pull/196).
> Qblox fixes for running circuits

- src/qibolab/_core/instruments/qblox/config/sequencer.py
Currently we are using the length of the probe waveform as the integration length, however this does not work well when the acquisition duration is significanly different than the probe duration. This modifies it to use the acquisition duration.
Here is an example from qw5q_platinum, where the probe duration is 300ns and the acquisition duration is 1200ns:
* before fix: http://login.qrccluster.com:9000/b5NGSyqVR_eNu3AVLwslvw==
* after fix: http://login.qrccluster.com:9000/1IS9bqNiThmAtdK37eo5WA==
> Match integration length to acquisition duration

- src/qibolab/_core/instruments/qm/controller.py
- src/qibolab/_core/sweeper.py
- tests/test_sweeper.py
Fixes the issue with the punchout routine reported in https://github.com/qiboteam/qibolab/issues/1272. 
For the absolute sweeper to work in an "absolute fashion" we need to register a sweeper with adjusted amplitude in the QM config. The problem was that this adjusted was implemented properly for `Pulse` objects, but not for `Readout` objects (needed for the punchout).
> Fix amplitude sweeper for `Readout` in QM
