qiboteam/qibolab

.github/workflows/selfhosted.yml
Same as #183 but pointing to `transpiler5q`.
=> fixing workflow for qpu

src/qibolab/pulses.py
This functionality is useful for debugging through the slurm queue
=> allowing all plot functions within pulses.py to save the plot as a .png file

src/qibolab/tests/test_transpilers_native.py, src/qibolab/transpilers/native.py
-Fix CU3 and CU2 native gate decomposition
-Added T, Tdg, S, Sdg and TOFFOLI native gate decomposition
-Added tests
-Modified tests, now native decomposition and original gates are compared excluding global phase factor
Checklist:
=> Fix transpiler_native

doc/source/conf.py
I have modified the `conf.py` in the doc folder selecting the Furo sphinx theme and setting the colors according to the web site.
When we are ready with the site we can merge this branch.
=> From rtd to furo sphinx theme

.github/workflows/deploy.yml, .github/workflows/rules.yml, .github/workflows/selfhosted.yml
In this PR, I'm taking into account issue #186. 
I have added python versions and the missing operative systems. 
Checklist:
=> Add workflows for multiple OS and python versions

doc/source/conf.py, doc/source/index.rst
In this PR:
- the text font is changed into "Ubuntu";
- the software's version is shown in the side-bar now.
=> New docs font and version display

doc/source/conf.py
=> Rm Ubuntu font from furo configuration

src/qibolab/runcards/tii1q_b4_200U.yml
I have done an initial characterization of the QPU, here is the runcard 
Checklist:
=> New runcard for SD 1q chip tii1q_b4_200U

src/qibolab/tests/test_transpilers_connectivity.py, src/qibolab/tests/test_transpilers_transpile.py, src/qibolab/transpilers/connectivity.py, src/qibolab/transpilers/transpile.py
=> Generic 5q hardware middle qubit

.github/codecov.yml
[Docs on Codecov](https://docs.codecov.com/docs/pull-request-comments#disable-comment) managed to confuse @andrea-pasquale, but they also confused myself...
Checklist:
=> Disable codecov PR comments

.github/workflows/deploy.yml, .github/workflows/rules.yml, pyproject.toml
This PR modify the workflows in order to use the ones stored in `qiboteam/workflows` (see qiboteam/workflows#23).
Checklist:
=> use reusable workflows

src/qibolab/backends.py, tests/test_backends.py
Same as qiboteam/qibo#817.
Checklist:
=> Pass circuits as initial state

setup.py, tests/test_transpilers_general.py
=> added seed to transpiler test

pyproject.toml, src/qibolab/__init__.py
=> updating and forwarding version

src/qibolab/transpilers/gate_decompositions.py, tests/test_transpilers_gate_decompositions.py
=> Fix identity decomposition

src/qibolab/platforms/multiqubit.py, src/qibolab/runcards/qw5q_gold_qblox.yml
This PR implements the fixes from #356 related to the qblox driver in order to merge them to main asap.
Let me know if you find more bugs.
Checklist:
=> Fixes for Qblox driver

.github/workflows/selfhosted.yml, qputests.sh
=> Fix self-runner

qputests.sh
=> Raise error on self-runner test

src/qibolab/instruments/erasynth.py
This PR solves a bug in the erasynth driver. Now it should work.
Maybe we could also change the name of the ethernet parameter to internet but I don't want to brake other drivers :-) 
Checklist:
=> erasynth driver fix

tests/conftest.py, tests/test_instruments_erasynth.py
@rodolfocarobene let's see if it works. If it does feel free to merge in your branch.
Checklist:
=> Fix ERA test

src/qibolab/platform.py, src/qibolab/runcards/tii1q_b1.yml
I should have already done this. It also enables testing of the new twpa optimization routine
Checklist:
=> Add TWPA to RFSoc4x2

src/qibolab/instruments/rfsoc.py, src/qibolab/platform.py, src/qibolab/pulses.py, src/qibolab/runcards/tii_zcu111.yml, tests/test_instruments_rfsoc.py
This PR extends the rfsoc driver to support multiplexed readout.
It should also provides support for sweeper on multiple pulses/biases and maybe 2D sweep
Checklist:
=> Zcu111 server multiplex

.github/workflows/deploy.yml, .github/workflows/publish.yml, .github/workflows/rules.yml, .github/workflows/selfhosted.yml
=> adding tests for python 3.11

.github/workflows/selfhosted.yml
=> Add workflow dispatch button to selfhosted runner

.github/workflows/publish.yml
This PR fixes https://github.com/qiboteam/qibolab/actions/runs/5135283010/jobs/9240498183#step:6:123
Checklist:
=> fix poetry-extras in publish.yml

src/qibolab/instruments/zhinst.py, tests/test_instruments_zhinst.py
From issue #475. For qibocal [333](https://github.com/qiboteam/qibocal/pull/333#discussion_r1211562306).
Checklist:
=> Start delay sweep

src/qibolab/instruments/qm.py, src/qibolab/instruments/zhinst.py, src/qibolab/sweeper.py, tests/test_instruments_qmsim.py, tests/test_instruments_zhinst.py
From https://github.com/qiboteam/qibolab/pull/481#issuecomment-1584754127.
Checklist:
=> Change delay sweeper to start sweeper

.pre-commit-config.yaml, README.md, doc/source/developer-guides/general.rst, doc/source/getting-started/lab.rst, src/qibolab/instruments/qblox.py, src/qibolab/pulses.py
This just applies Black in the docstrings and documentation snippets.
Checklist:
=> Add blacken-docs hook

.pre-commit-config.yaml, src/qibolab/instruments/erasynth.py, src/qibolab/instruments/icarusq.py, src/qibolab/instruments/qutech.py, src/qibolab/instruments/rohde_schwarz.py, src/qibolab/pulses.py
I wanted to start properly formatting docstrings, but I don't want to cause massive changes right now.
For this reason, I restricted the scope of `pydocstyle` to a minimal subset of checks. The plan is to gradually extend these checks to cover the full set.
To be merged after #482 (of course)
Checklist:
=> Add pydocstyle hook

poetry.lock, pyproject.toml, src/qibolab/instruments/rfsoc.py, tests/test_instruments_rfsoc.py
Reflect changes that are now under development in https://github.com/qiboteam/qibosoq/pull/54.
This should help adding support for custom pulses.
Without changing too much the layout of the driver, I ended up doing maybe something weird... but I am not sure which is the better way to do it
Checklist:
=> Rfsoc shape classes

src/qibolab/qubits.py
Change name from alpha to anharmonicity as per @aorgazf desires
Checklist:
=> change name

poetry.lock, pyproject.toml, src/qibolab/instruments/rfsoc.py, tests/test_instruments_rfsoc.py
Reflect the changes in qibosoq (https://github.com/qiboteam/qibosoq/pull/52).
With this PR all the pulse timing are moved from absolute to relative
Checklist:
=> Rfsoc pulse timed abs -> relative

poetry.lock, pyproject.toml, src/qibolab/instruments/rfsoc.py, tests/test_instruments_rfsoc.py
=> Update rfsoc driver for new qibosoq

src/qibolab/instruments/erasynth.py
Should fix #516. I've followed some answers [here](https://stackoverflow.com/questions/28377421/why-do-i-receive-a-timeout-error-from-pythons-requests-module). 
For me the problem seems solved/much less relevant, but could you also try this please, @Jacfomg?
Checklist:
=> Fix Erasynth issues

src/qibolab/instruments/rfsoc/convert.py, tests/test_instruments_rfsoc.py
Following [Andrea's comment](https://github.com/qiboteam/qibolab/pull/520#discussion_r1258266932) in #520, I tried to implement a nicer overloaded convert function. 
Still untested at the moment
Checklist:
=> RFSoC overloading

src/qibolab/instruments/zhinst.py, tests/test_instruments_zhinst.py
Sampled pulses zh. I will check with the scope for a SNZ pulse. I believe we will have custom pulses if the qblox pr gets merged.
Checklist:
=> Sampled pulses zh

src/qibolab/instruments/zhinst.py
I messed up with one `copy`, there must be a nicer way but I needed something working for next week.
Checklist:
=> fix amp factor sweepers zurich

src/qibolab/compilers/compiler.py, src/qibolab/compilers/default.py, src/qibolab/transpilers/gate_decompositions.py, tests/test_compilers_default.py, tests/test_transpilers_gate_decompositions.py
Closes #548. 
I don't have a specific reference but according to what I saw in https://github.com/qiboteam/qibocal/pull/452 it should be correct.
Checklist:
=> Implement GPI2 gate in transpiler

src/qibolab/native.py, src/qibolab/pulses.py, src/qibolab/serialize.py, tests/dummy_qrc/qblox.py, tests/dummy_qrc/qblox.yml, tests/dummy_qrc/qm.py, tests/dummy_qrc/qm.yml, tests/dummy_qrc/rfsoc.py, tests/dummy_qrc/rfsoc.yml, tests/dummy_qrc/zurich.py, tests/dummy_qrc/zurich.yml, tests/test_platform.py
Fixes #565 and adds a relevant test.
Checklist:
=> Fix and test runcard dump

poetry.lock, src/qibolab/transpilers/gate_decompositions.py, src/qibolab/transpilers/star_connectivity.py, tests/test_compilers_default.py, tests/test_transpilers_gate_decompositions.py, tests/test_transpilers_unitary_decompositions.py
Update needed due to https://github.com/qiboteam/qibo/pull/985
Checklist:
=> Rename asmatrix to matrix

.pre-commit-config.yaml
Originally done by @AleCandido for #588 but not pushed.
Checklist:
=> Add check-toml in pre-commit

doc/source/tutorials/lab.rst, doc/source/tutorials/pulses.rst, src/qibolab/pulses.py
=> Fix pulse tutorial in docs and bug with sequence plotting

src/qibolab/instruments/zhinst.py
Needs debugging on the routines and timing perfomance comparison
Checklist:
=> Connection only once per routine - Zurich

src/qibolab/dummy.py, src/qibolab/native.py, src/qibolab/platform.py, tests/dummy_qrc/qblox.yml, tests/dummy_qrc/qm.yml, tests/dummy_qrc/rfsoc.yml, tests/dummy_qrc/zurich.yml, tests/test_dummy.py
Closes #602.
Maybe the name for the pulse is not the best.
Let me know if you have a better idea.
@stavros11 concerning coverage should I just write a test for the new pulse?
Checklist:
=> Adding `RX12` pulse

src/qibolab/qubits.py
Add `qutrit_classifiers_hpars` attribute
Checklist:
=> qutrit classifiers hpars

src/qibolab/dummy.yml
=> Add missing RX12 pulse to dummy

src/qibolab/pulses.py
This PR introduces some changes to the Custom PulseShape. Previously the same arbitrary shape was applied to both the i and q components, but in some applications, it would be desirable to be able to set each independently.
It also changes the way pulses are copied. Previously it was trying to create copies of the pulse shape using the representation string (for instance `Rectangular()`) but that didn't work with pulses like custom, so it now uses `copy` library
Checklist:
=> Extend the functionality of custom pulses

poetry.lock, pyproject.toml
Fixes numpy version correctly (unlike what I did #630)
Checklist:
=> Hotfix for #630

src/qibolab/instruments/zhinst.py
Patch for new update.
Checklist:
=> patch for zurich probabilities

src/qibolab/instruments/zhinst.py
=> Typos in some docstrings

doc/source/main-documentation/qibolab.rst, src/qibolab/__init__.py, src/qibolab/dummy.py, src/qibolab/instruments/dummy.py, src/qibolab/instruments/qblox/controller.py, src/qibolab/instruments/qm/driver.py, src/qibolab/instruments/rfsoc/driver.py, src/qibolab/platform.py, src/qibolab/serialize.py, tests/test_dummy.py, tests/test_instruments_qm.py, tests/test_instruments_rfsoc.py
Fixes #645. I had to put the couplers in all instruments `play` to unify their interface, that's why the files changed are more than expected.
Checklist:
=> Dummy without couplers

src/qibolab/instruments/zhinst.py
Not sure if this is due to the new version or something went wrong with the other fix. Anyhow,
Zeno working again. It would be good to have it merged soon.
Checklist:
=> fix ros2 zurich

src/qibolab/pulses.py, tests/test_pulses.py
=> Allow float duration and start time in pulses

src/qibolab/instruments/qblox/cluster_qcm_bb.py, src/qibolab/instruments/qblox/cluster_qcm_rf.py, src/qibolab/instruments/qblox/cluster_qrm_rf.py, src/qibolab/instruments/qblox/controller.py, src/qibolab/instruments/qblox/port.py, tests/dummy_qrc/qblox.py, tests/dummy_qrc/qblox.yml
This PR implement the channel instantiation refactoring suggested by @stavros11, and the effect on the `create`  method are visible in PR https://github.com/qiboteam/qibolab_platforms_qrc/pull/87. 
It's only refactoring and should not break any routine, I've tested some of them and they are performing as expected. 
Should be merged after PR #640 
Checklist:
=> Refactor channel map Qblox

poetry.lock, pyproject.toml
Update LabOneQ version for their patch. The number of measurements for 5 qubits is greater than 100 but smaller than 500, @GabrielePalazzo maybe getting a better estimate would be nice.
Checklist:
=> fix zurich update

src/qibolab/instruments/zhinst.py
=> Swapping correct sweepers axes with singleshot averaging_mode

src/qibolab/instruments/abstract.py, src/qibolab/instruments/dummy.py, src/qibolab/instruments/qblox/controller.py, src/qibolab/instruments/qm/driver.py, src/qibolab/instruments/rfsoc/driver.py, src/qibolab/instruments/zhinst.py, src/qibolab/platform.py, tests/test_platform.py
Potentially useful for https://github.com/qiboteam/qibocal/pull/679#pullrequestreview-1796424370
Checklist:
=> Sampling rate as platform property

src/qibolab/instruments/qblox/port.py
This PR close #726.
Report to check that all is working: http://login.qrccluster.com:9000/DJxQsDoSRqKd5OgDh3KVzg==
Checklist:
=> Remove query to devices to get port values

src/qibolab/instruments/qblox/cluster_qcm_bb.py
=> Minor code simplification

src/qibolab/pulses.py, tests/test_pulses.py
Following @PiergiorgioButtarini removal of last usage in Qblox, in #729
=> Remove `_if` from `Pulse`

src/qibolab/platform.py, tests/test_dummy.py, tests/test_platform.py
=> Adding flux pulse creation in the platform

tests/test_backends.py
Fixes #657 by adding some tests that confirm that the required points work.
=> Some circuit tests

src/qibolab/instruments/bluefors.py, tests/test_instruments_bluefors.py
@alecandido, @scarrazza, @stavros11 if you agree, we should continue here.
Checklist:
=> Bluefors cryo temperature controller

src/qibolab/instruments/bluefors.py
In this pull request I include a driver to retrieve data from Bluefors Temperature Controller.
```python
from qibolab.instruments.bluefors import TemperatureController
import time
tc = TemperatureController('192.168.0.114') # XLD1000 Temperature Controller
while True:
time.sleep(10)
print("latest data")
print(tc.data)
```
Checklist:
=> Bluefors Temperature Controller

src/qibolab/instruments/qblox/controller.py, tests/test_instruments_qblox_controller.py
Fixes https://github.com/qiboteam/qibolab/issues/850
Checklist:
=> reduce the max number of bins

.github/workflows/rules.yml
=> updating ci rule for PRs

src/qibolab/backends.py, tests/test_backends.py
This PR closes #893 
Checklist:
=> Rename initial_state in execute_circuits

src/qibolab/qubits.py
As title says. Related to https://github.com/qiboteam/qibolab_platforms_qrc/pull/135
Checklist:
=> Add resonator depletion time to Qubit class

src/qibolab/instruments/qm/config.py, src/qibolab/instruments/qm/controller.py, src/qibolab/instruments/qm/sequence.py, tests/test_instruments_qm.py
I am not sure if I would merge that because it was a very quick and messy fix, but we should certainly support it on all drivers for 0.2
=> Hotfix to allow playing different frequencies on the same qubit with QM

tests/emulators/default_q0/parameters.json, tests/emulators/ibmfakebelem_q01/parameters.json
Updated both runcards for the emulator platforms.
Checklist:
=> Update emulator runcards

doc/source/tutorials/compiler.rst, src/qibolab/compilers/compiler.py, src/qibolab/compilers/default.py, tests/test_backends.py, tests/test_compilers_default.py
=> Remove U3 rule from default compiler

doc/source/getting-started/experiment.rst, doc/source/main-documentation/qibolab.rst, doc/source/tutorials/calibration.rst, src/qibolab/instruments/dummy.py, src/qibolab/platform/platform.py, src/qibolab/sweeper.py, tests/test_dummy.py, tests/test_result_shapes.py
=> Diagonal sweepers

doc/source/getting-started/experiment.rst, doc/source/tutorials/lab.rst, src/qibolab/components/channels.py, src/qibolab/dummy/platform.py, src/qibolab/instruments/qm/config/config.py, src/qibolab/instruments/qm/controller.py, src/qibolab/instruments/zhinst/executor.py, tests/dummy_qrc/zurich/platform.py
=> Rename `AcquireChannel` to `AcquisitionChannel`

crate/src/lib.rs
=> Fix Rust workflow

src/qibolab/dummy/parameters.json
=> Change targets in dummy virtual z corrections

src/qibolab/_core/instruments/emulator/hamiltonians.py
=> FIxing pulse amplitude handling in emulator

src/qibolab/_core/instruments/emulator/emulator.py, src/qibolab/_core/instruments/emulator/hamiltonians.py
I just realized that with the emulator we were ignoring  `VirtualZ` pulses.
This PR fixes the issue. As a test I manage to run a single qubit RB with the emulator.
Running the RB requires a small fix on the qibocal transpilation side: https://github.com/qiboteam/qibocal/pull/1115
=> Adding virtual Z pulses to emulator

src/qibolab/_core/pulses/plot.py
=> Fix `sequence` plotting function

src/qibolab/_core/instruments/emulator/engine/abstract.py, src/qibolab/_core/instruments/emulator/engine/qutip.py
=> add kwargs to QutipEngine.evolve method

src/qibolab/_core/platform/platform.py
Propagates #1110 to 0.2. I am not sure why we have not done this before and what was the exact plan, however based on lab requirements it seems to be useful to avoid in some cases, particularly to avoid increasing the temperature (particularly with the current SPI related experiments).
=> Disconnect platform when job is interrupted

src/qibolab/_core/components/__init__.py, src/qibolab/_core/components/configs.py, src/qibolab/_core/components/filters.py, src/qibolab/_core/instruments/qm/components/configs.py, src/qibolab/_core/instruments/qm/config/config.py
This PR introduces an API for predistorsion filters. Currently I've added just an `ExponentialFilter` and a `FiniteImpulseResponseFilter` which are the only one used in Qibocal at the moment.
Tests and documentation are still missing, as soon as we are happy with the API I will provide them as well.
=> Proposal for `Filters` API
